package com.woniuxy.mapper;

import com.woniuxy.entity.Assemble;
import com.woniuxy.entity.AssembleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssembleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int countByExample(AssembleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByExample(AssembleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByPrimaryKey(Integer p6Aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insert(Assemble record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insertSelective(Assemble record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<Assemble> selectByExampleWithBLOBs(AssembleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<Assemble> selectByExample(AssembleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    Assemble selectByPrimaryKey(Integer p6Aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") Assemble record, @Param("example") AssembleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Assemble record, @Param("example") AssembleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExample(@Param("record") Assemble record, @Param("example") AssembleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(Assemble record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Assemble record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKey(Assemble record);
}