package com.woniuxy.mapper;

import com.woniuxy.entity.AssembleStock;
import com.woniuxy.entity.AssembleStockExample;
import com.woniuxy.entity.AssembleStockKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssembleStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int countByExample(AssembleStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByExample(AssembleStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByPrimaryKey(AssembleStockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insert(AssembleStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insertSelective(AssembleStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<AssembleStock> selectByExample(AssembleStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    AssembleStock selectByPrimaryKey(AssembleStockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") AssembleStock record, @Param("example") AssembleStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExample(@Param("record") AssembleStock record, @Param("example") AssembleStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(AssembleStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assemble_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKey(AssembleStock record);
}