package com.woniuxy.mapper;

import com.woniuxy.entity.Craneman;
import com.woniuxy.entity.CranemanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CranemanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int countByExample(CranemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByExample(CranemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByPrimaryKey(Integer cmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insert(Craneman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insertSelective(Craneman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<Craneman> selectByExample(CranemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    Craneman selectByPrimaryKey(Integer cmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") Craneman record, @Param("example") CranemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExample(@Param("record") Craneman record, @Param("example") CranemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(Craneman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKey(Craneman record);
}