package com.woniuxy.mapper;

import com.woniuxy.entity.EmbedmentStock;
import com.woniuxy.entity.EmbedmentStockExample;
import com.woniuxy.entity.EmbedmentStockKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmbedmentStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int countByExample(EmbedmentStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByExample(EmbedmentStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByPrimaryKey(EmbedmentStockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insert(EmbedmentStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insertSelective(EmbedmentStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<EmbedmentStock> selectByExample(EmbedmentStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    EmbedmentStock selectByPrimaryKey(EmbedmentStockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") EmbedmentStock record, @Param("example") EmbedmentStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExample(@Param("record") EmbedmentStock record, @Param("example") EmbedmentStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(EmbedmentStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKey(EmbedmentStock record);
}