package com.woniuxy.mapper;

import com.woniuxy.entity.Embedment;
import com.woniuxy.entity.EmbedmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmbedmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int countByExample(EmbedmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByExample(EmbedmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByPrimaryKey(Integer p3Eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insert(Embedment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insertSelective(Embedment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<Embedment> selectByExampleWithBLOBs(EmbedmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<Embedment> selectByExample(EmbedmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    Embedment selectByPrimaryKey(Integer p3Eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") Embedment record, @Param("example") EmbedmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Embedment record, @Param("example") EmbedmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExample(@Param("record") Embedment record, @Param("example") EmbedmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(Embedment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Embedment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKey(Embedment record);
}