package com.woniuxy.mapper;

import com.woniuxy.entity.PaintingStock;
import com.woniuxy.entity.PaintingStockExample;
import com.woniuxy.entity.PaintingStockKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaintingStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int countByExample(PaintingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByExample(PaintingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByPrimaryKey(PaintingStockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insert(PaintingStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insertSelective(PaintingStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<PaintingStock> selectByExample(PaintingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    PaintingStock selectByPrimaryKey(PaintingStockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") PaintingStock record, @Param("example") PaintingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExample(@Param("record") PaintingStock record, @Param("example") PaintingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(PaintingStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKey(PaintingStock record);
}