package com.woniuxy.mapper;

import com.woniuxy.entity.Party;
import com.woniuxy.entity.PartyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int countByExample(PartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByExample(PartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByPrimaryKey(Integer company);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insert(Party record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insertSelective(Party record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<Party> selectByExample(PartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    Party selectByPrimaryKey(Integer company);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") Party record, @Param("example") PartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExample(@Param("record") Party record, @Param("example") PartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(Party record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKey(Party record);
}