package com.woniuxy.mapper;

import com.woniuxy.entity.Pit;
import com.woniuxy.entity.PitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int countByExample(PitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByExample(PitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByPrimaryKey(Integer p2Pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insert(Pit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insertSelective(Pit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<Pit> selectByExampleWithBLOBs(PitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<Pit> selectByExample(PitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    Pit selectByPrimaryKey(Integer p2Pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") Pit record, @Param("example") PitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Pit record, @Param("example") PitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExample(@Param("record") Pit record, @Param("example") PitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(Pit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Pit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKey(Pit record);
}