package com.woniuxy.mapper;

import com.woniuxy.entity.PitStock;
import com.woniuxy.entity.PitStockExample;
import com.woniuxy.entity.PitStockKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PitStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int countByExample(PitStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByExample(PitStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByPrimaryKey(PitStockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insert(PitStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insertSelective(PitStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<PitStock> selectByExample(PitStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    PitStock selectByPrimaryKey(PitStockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") PitStock record, @Param("example") PitStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExample(@Param("record") PitStock record, @Param("example") PitStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(PitStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pit_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKey(PitStock record);
}