package com.woniuxy.mapper;

import com.woniuxy.entity.Projectman;
import com.woniuxy.entity.ProjectmanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int countByExample(ProjectmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByExample(ProjectmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByPrimaryKey(Integer pmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insert(Projectman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insertSelective(Projectman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<Projectman> selectByExample(ProjectmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    Projectman selectByPrimaryKey(Integer pmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") Projectman record, @Param("example") ProjectmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExample(@Param("record") Projectman record, @Param("example") ProjectmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(Projectman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKey(Projectman record);
}