package com.woniuxy.mapper;

import com.woniuxy.entity.Splicing;
import com.woniuxy.entity.SplicingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SplicingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int countByExample(SplicingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByExample(SplicingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByPrimaryKey(Integer p4Spid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insert(Splicing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insertSelective(Splicing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<Splicing> selectByExampleWithBLOBs(SplicingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<Splicing> selectByExample(SplicingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    Splicing selectByPrimaryKey(Integer p4Spid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") Splicing record, @Param("example") SplicingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Splicing record, @Param("example") SplicingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExample(@Param("record") Splicing record, @Param("example") SplicingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(Splicing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Splicing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKey(Splicing record);
}