package com.woniuxy.mapper;

import com.woniuxy.entity.SplicingStock;
import com.woniuxy.entity.SplicingStockExample;
import com.woniuxy.entity.SplicingStockKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SplicingStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int countByExample(SplicingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByExample(SplicingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByPrimaryKey(SplicingStockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insert(SplicingStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insertSelective(SplicingStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<SplicingStock> selectByExample(SplicingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    SplicingStock selectByPrimaryKey(SplicingStockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SplicingStock record, @Param("example") SplicingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExample(@Param("record") SplicingStock record, @Param("example") SplicingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(SplicingStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table splicing_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKey(SplicingStock record);
}