package com.woniuxy.mapper;

import com.woniuxy.entity.Welding;
import com.woniuxy.entity.WeldingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeldingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int countByExample(WeldingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByExample(WeldingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByPrimaryKey(Integer p5Wid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insert(Welding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insertSelective(Welding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<Welding> selectByExampleWithBLOBs(WeldingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<Welding> selectByExample(WeldingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    Welding selectByPrimaryKey(Integer p5Wid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") Welding record, @Param("example") WeldingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Welding record, @Param("example") WeldingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExample(@Param("record") Welding record, @Param("example") WeldingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(Welding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Welding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKey(Welding record);
}