package com.woniuxy.mapper;

import com.woniuxy.entity.WeldingStock;
import com.woniuxy.entity.WeldingStockExample;
import com.woniuxy.entity.WeldingStockKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeldingStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int countByExample(WeldingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByExample(WeldingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int deleteByPrimaryKey(WeldingStockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insert(WeldingStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int insertSelective(WeldingStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    List<WeldingStock> selectByExample(WeldingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    WeldingStock selectByPrimaryKey(WeldingStockKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") WeldingStock record, @Param("example") WeldingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByExample(@Param("record") WeldingStock record, @Param("example") WeldingStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(WeldingStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table welding_stock
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    int updateByPrimaryKey(WeldingStock record);
}