package com.woniuxy.entity;

public class AssembleStockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_stock.p6_aid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer p6Aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_stock.p6_aid
     *
     * @return the value of assemble_stock.p6_aid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getP6Aid() {
        return p6Aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_stock.p6_aid
     *
     * @param p6Aid the value for assemble_stock.p6_aid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP6Aid(Integer p6Aid) {
        this.p6Aid = p6Aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble_stock.sid
     *
     * @return the value of assemble_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble_stock.sid
     *
     * @param sid the value for assemble_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }
}