package com.woniuxy.entity;

public class Assemble {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble.p6_aid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer p6Aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble.p6_aname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p6Aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble.p6_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p6Status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assemble.p6_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p6Remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble.p6_aid
     *
     * @return the value of assemble.p6_aid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getP6Aid() {
        return p6Aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble.p6_aid
     *
     * @param p6Aid the value for assemble.p6_aid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP6Aid(Integer p6Aid) {
        this.p6Aid = p6Aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble.project_id
     *
     * @return the value of assemble.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble.project_id
     *
     * @param projectId the value for assemble.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble.p6_aname
     *
     * @return the value of assemble.p6_aname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP6Aname() {
        return p6Aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble.p6_aname
     *
     * @param p6Aname the value for assemble.p6_aname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP6Aname(String p6Aname) {
        this.p6Aname = p6Aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble.p6_status
     *
     * @return the value of assemble.p6_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP6Status() {
        return p6Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble.p6_status
     *
     * @param p6Status the value for assemble.p6_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP6Status(String p6Status) {
        this.p6Status = p6Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble.company
     *
     * @return the value of assemble.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble.company
     *
     * @param company the value for assemble.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assemble.p6_remarks
     *
     * @return the value of assemble.p6_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP6Remarks() {
        return p6Remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assemble.p6_remarks
     *
     * @param p6Remarks the value for assemble.p6_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP6Remarks(String p6Remarks) {
        this.p6Remarks = p6Remarks;
    }
}