package com.woniuxy.entity;

import java.math.BigDecimal;

public class Constructionman {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constructionman.csc_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer cscId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constructionman.fm_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer fmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constructionman.csc_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String cscName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constructionman.csc_sex
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String cscSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constructionman.csc_age
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer cscAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constructionman.csc_phone
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer cscPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constructionman.csc_sal
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private BigDecimal cscSal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constructionman.csc_address
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String cscAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constructionman.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constructionman.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constructionman.csc_id
     *
     * @return the value of constructionman.csc_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCscId() {
        return cscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constructionman.csc_id
     *
     * @param cscId the value for constructionman.csc_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCscId(Integer cscId) {
        this.cscId = cscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constructionman.fm_id
     *
     * @return the value of constructionman.fm_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getFmId() {
        return fmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constructionman.fm_id
     *
     * @param fmId the value for constructionman.fm_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setFmId(Integer fmId) {
        this.fmId = fmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constructionman.csc_name
     *
     * @return the value of constructionman.csc_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getCscName() {
        return cscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constructionman.csc_name
     *
     * @param cscName the value for constructionman.csc_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCscName(String cscName) {
        this.cscName = cscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constructionman.csc_sex
     *
     * @return the value of constructionman.csc_sex
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getCscSex() {
        return cscSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constructionman.csc_sex
     *
     * @param cscSex the value for constructionman.csc_sex
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCscSex(String cscSex) {
        this.cscSex = cscSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constructionman.csc_age
     *
     * @return the value of constructionman.csc_age
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCscAge() {
        return cscAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constructionman.csc_age
     *
     * @param cscAge the value for constructionman.csc_age
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCscAge(Integer cscAge) {
        this.cscAge = cscAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constructionman.csc_phone
     *
     * @return the value of constructionman.csc_phone
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCscPhone() {
        return cscPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constructionman.csc_phone
     *
     * @param cscPhone the value for constructionman.csc_phone
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCscPhone(Integer cscPhone) {
        this.cscPhone = cscPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constructionman.csc_sal
     *
     * @return the value of constructionman.csc_sal
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public BigDecimal getCscSal() {
        return cscSal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constructionman.csc_sal
     *
     * @param cscSal the value for constructionman.csc_sal
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCscSal(BigDecimal cscSal) {
        this.cscSal = cscSal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constructionman.csc_address
     *
     * @return the value of constructionman.csc_address
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getCscAddress() {
        return cscAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constructionman.csc_address
     *
     * @param cscAddress the value for constructionman.csc_address
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCscAddress(String cscAddress) {
        this.cscAddress = cscAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constructionman.status
     *
     * @return the value of constructionman.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constructionman.status
     *
     * @param status the value for constructionman.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constructionman.company
     *
     * @return the value of constructionman.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constructionman.company
     *
     * @param company the value for constructionman.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }
}