package com.woniuxy.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ConstructionmanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public ConstructionmanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCscIdIsNull() {
            addCriterion("csc_id is null");
            return (Criteria) this;
        }

        public Criteria andCscIdIsNotNull() {
            addCriterion("csc_id is not null");
            return (Criteria) this;
        }

        public Criteria andCscIdEqualTo(Integer value) {
            addCriterion("csc_id =", value, "cscId");
            return (Criteria) this;
        }

        public Criteria andCscIdNotEqualTo(Integer value) {
            addCriterion("csc_id <>", value, "cscId");
            return (Criteria) this;
        }

        public Criteria andCscIdGreaterThan(Integer value) {
            addCriterion("csc_id >", value, "cscId");
            return (Criteria) this;
        }

        public Criteria andCscIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("csc_id >=", value, "cscId");
            return (Criteria) this;
        }

        public Criteria andCscIdLessThan(Integer value) {
            addCriterion("csc_id <", value, "cscId");
            return (Criteria) this;
        }

        public Criteria andCscIdLessThanOrEqualTo(Integer value) {
            addCriterion("csc_id <=", value, "cscId");
            return (Criteria) this;
        }

        public Criteria andCscIdIn(List<Integer> values) {
            addCriterion("csc_id in", values, "cscId");
            return (Criteria) this;
        }

        public Criteria andCscIdNotIn(List<Integer> values) {
            addCriterion("csc_id not in", values, "cscId");
            return (Criteria) this;
        }

        public Criteria andCscIdBetween(Integer value1, Integer value2) {
            addCriterion("csc_id between", value1, value2, "cscId");
            return (Criteria) this;
        }

        public Criteria andCscIdNotBetween(Integer value1, Integer value2) {
            addCriterion("csc_id not between", value1, value2, "cscId");
            return (Criteria) this;
        }

        public Criteria andFmIdIsNull() {
            addCriterion("fm_id is null");
            return (Criteria) this;
        }

        public Criteria andFmIdIsNotNull() {
            addCriterion("fm_id is not null");
            return (Criteria) this;
        }

        public Criteria andFmIdEqualTo(Integer value) {
            addCriterion("fm_id =", value, "fmId");
            return (Criteria) this;
        }

        public Criteria andFmIdNotEqualTo(Integer value) {
            addCriterion("fm_id <>", value, "fmId");
            return (Criteria) this;
        }

        public Criteria andFmIdGreaterThan(Integer value) {
            addCriterion("fm_id >", value, "fmId");
            return (Criteria) this;
        }

        public Criteria andFmIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fm_id >=", value, "fmId");
            return (Criteria) this;
        }

        public Criteria andFmIdLessThan(Integer value) {
            addCriterion("fm_id <", value, "fmId");
            return (Criteria) this;
        }

        public Criteria andFmIdLessThanOrEqualTo(Integer value) {
            addCriterion("fm_id <=", value, "fmId");
            return (Criteria) this;
        }

        public Criteria andFmIdIn(List<Integer> values) {
            addCriterion("fm_id in", values, "fmId");
            return (Criteria) this;
        }

        public Criteria andFmIdNotIn(List<Integer> values) {
            addCriterion("fm_id not in", values, "fmId");
            return (Criteria) this;
        }

        public Criteria andFmIdBetween(Integer value1, Integer value2) {
            addCriterion("fm_id between", value1, value2, "fmId");
            return (Criteria) this;
        }

        public Criteria andFmIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fm_id not between", value1, value2, "fmId");
            return (Criteria) this;
        }

        public Criteria andCscNameIsNull() {
            addCriterion("csc_name is null");
            return (Criteria) this;
        }

        public Criteria andCscNameIsNotNull() {
            addCriterion("csc_name is not null");
            return (Criteria) this;
        }

        public Criteria andCscNameEqualTo(String value) {
            addCriterion("csc_name =", value, "cscName");
            return (Criteria) this;
        }

        public Criteria andCscNameNotEqualTo(String value) {
            addCriterion("csc_name <>", value, "cscName");
            return (Criteria) this;
        }

        public Criteria andCscNameGreaterThan(String value) {
            addCriterion("csc_name >", value, "cscName");
            return (Criteria) this;
        }

        public Criteria andCscNameGreaterThanOrEqualTo(String value) {
            addCriterion("csc_name >=", value, "cscName");
            return (Criteria) this;
        }

        public Criteria andCscNameLessThan(String value) {
            addCriterion("csc_name <", value, "cscName");
            return (Criteria) this;
        }

        public Criteria andCscNameLessThanOrEqualTo(String value) {
            addCriterion("csc_name <=", value, "cscName");
            return (Criteria) this;
        }

        public Criteria andCscNameLike(String value) {
            addCriterion("csc_name like", value, "cscName");
            return (Criteria) this;
        }

        public Criteria andCscNameNotLike(String value) {
            addCriterion("csc_name not like", value, "cscName");
            return (Criteria) this;
        }

        public Criteria andCscNameIn(List<String> values) {
            addCriterion("csc_name in", values, "cscName");
            return (Criteria) this;
        }

        public Criteria andCscNameNotIn(List<String> values) {
            addCriterion("csc_name not in", values, "cscName");
            return (Criteria) this;
        }

        public Criteria andCscNameBetween(String value1, String value2) {
            addCriterion("csc_name between", value1, value2, "cscName");
            return (Criteria) this;
        }

        public Criteria andCscNameNotBetween(String value1, String value2) {
            addCriterion("csc_name not between", value1, value2, "cscName");
            return (Criteria) this;
        }

        public Criteria andCscSexIsNull() {
            addCriterion("csc_sex is null");
            return (Criteria) this;
        }

        public Criteria andCscSexIsNotNull() {
            addCriterion("csc_sex is not null");
            return (Criteria) this;
        }

        public Criteria andCscSexEqualTo(String value) {
            addCriterion("csc_sex =", value, "cscSex");
            return (Criteria) this;
        }

        public Criteria andCscSexNotEqualTo(String value) {
            addCriterion("csc_sex <>", value, "cscSex");
            return (Criteria) this;
        }

        public Criteria andCscSexGreaterThan(String value) {
            addCriterion("csc_sex >", value, "cscSex");
            return (Criteria) this;
        }

        public Criteria andCscSexGreaterThanOrEqualTo(String value) {
            addCriterion("csc_sex >=", value, "cscSex");
            return (Criteria) this;
        }

        public Criteria andCscSexLessThan(String value) {
            addCriterion("csc_sex <", value, "cscSex");
            return (Criteria) this;
        }

        public Criteria andCscSexLessThanOrEqualTo(String value) {
            addCriterion("csc_sex <=", value, "cscSex");
            return (Criteria) this;
        }

        public Criteria andCscSexLike(String value) {
            addCriterion("csc_sex like", value, "cscSex");
            return (Criteria) this;
        }

        public Criteria andCscSexNotLike(String value) {
            addCriterion("csc_sex not like", value, "cscSex");
            return (Criteria) this;
        }

        public Criteria andCscSexIn(List<String> values) {
            addCriterion("csc_sex in", values, "cscSex");
            return (Criteria) this;
        }

        public Criteria andCscSexNotIn(List<String> values) {
            addCriterion("csc_sex not in", values, "cscSex");
            return (Criteria) this;
        }

        public Criteria andCscSexBetween(String value1, String value2) {
            addCriterion("csc_sex between", value1, value2, "cscSex");
            return (Criteria) this;
        }

        public Criteria andCscSexNotBetween(String value1, String value2) {
            addCriterion("csc_sex not between", value1, value2, "cscSex");
            return (Criteria) this;
        }

        public Criteria andCscAgeIsNull() {
            addCriterion("csc_age is null");
            return (Criteria) this;
        }

        public Criteria andCscAgeIsNotNull() {
            addCriterion("csc_age is not null");
            return (Criteria) this;
        }

        public Criteria andCscAgeEqualTo(Integer value) {
            addCriterion("csc_age =", value, "cscAge");
            return (Criteria) this;
        }

        public Criteria andCscAgeNotEqualTo(Integer value) {
            addCriterion("csc_age <>", value, "cscAge");
            return (Criteria) this;
        }

        public Criteria andCscAgeGreaterThan(Integer value) {
            addCriterion("csc_age >", value, "cscAge");
            return (Criteria) this;
        }

        public Criteria andCscAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("csc_age >=", value, "cscAge");
            return (Criteria) this;
        }

        public Criteria andCscAgeLessThan(Integer value) {
            addCriterion("csc_age <", value, "cscAge");
            return (Criteria) this;
        }

        public Criteria andCscAgeLessThanOrEqualTo(Integer value) {
            addCriterion("csc_age <=", value, "cscAge");
            return (Criteria) this;
        }

        public Criteria andCscAgeIn(List<Integer> values) {
            addCriterion("csc_age in", values, "cscAge");
            return (Criteria) this;
        }

        public Criteria andCscAgeNotIn(List<Integer> values) {
            addCriterion("csc_age not in", values, "cscAge");
            return (Criteria) this;
        }

        public Criteria andCscAgeBetween(Integer value1, Integer value2) {
            addCriterion("csc_age between", value1, value2, "cscAge");
            return (Criteria) this;
        }

        public Criteria andCscAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("csc_age not between", value1, value2, "cscAge");
            return (Criteria) this;
        }

        public Criteria andCscPhoneIsNull() {
            addCriterion("csc_phone is null");
            return (Criteria) this;
        }

        public Criteria andCscPhoneIsNotNull() {
            addCriterion("csc_phone is not null");
            return (Criteria) this;
        }

        public Criteria andCscPhoneEqualTo(Integer value) {
            addCriterion("csc_phone =", value, "cscPhone");
            return (Criteria) this;
        }

        public Criteria andCscPhoneNotEqualTo(Integer value) {
            addCriterion("csc_phone <>", value, "cscPhone");
            return (Criteria) this;
        }

        public Criteria andCscPhoneGreaterThan(Integer value) {
            addCriterion("csc_phone >", value, "cscPhone");
            return (Criteria) this;
        }

        public Criteria andCscPhoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("csc_phone >=", value, "cscPhone");
            return (Criteria) this;
        }

        public Criteria andCscPhoneLessThan(Integer value) {
            addCriterion("csc_phone <", value, "cscPhone");
            return (Criteria) this;
        }

        public Criteria andCscPhoneLessThanOrEqualTo(Integer value) {
            addCriterion("csc_phone <=", value, "cscPhone");
            return (Criteria) this;
        }

        public Criteria andCscPhoneIn(List<Integer> values) {
            addCriterion("csc_phone in", values, "cscPhone");
            return (Criteria) this;
        }

        public Criteria andCscPhoneNotIn(List<Integer> values) {
            addCriterion("csc_phone not in", values, "cscPhone");
            return (Criteria) this;
        }

        public Criteria andCscPhoneBetween(Integer value1, Integer value2) {
            addCriterion("csc_phone between", value1, value2, "cscPhone");
            return (Criteria) this;
        }

        public Criteria andCscPhoneNotBetween(Integer value1, Integer value2) {
            addCriterion("csc_phone not between", value1, value2, "cscPhone");
            return (Criteria) this;
        }

        public Criteria andCscSalIsNull() {
            addCriterion("csc_sal is null");
            return (Criteria) this;
        }

        public Criteria andCscSalIsNotNull() {
            addCriterion("csc_sal is not null");
            return (Criteria) this;
        }

        public Criteria andCscSalEqualTo(BigDecimal value) {
            addCriterion("csc_sal =", value, "cscSal");
            return (Criteria) this;
        }

        public Criteria andCscSalNotEqualTo(BigDecimal value) {
            addCriterion("csc_sal <>", value, "cscSal");
            return (Criteria) this;
        }

        public Criteria andCscSalGreaterThan(BigDecimal value) {
            addCriterion("csc_sal >", value, "cscSal");
            return (Criteria) this;
        }

        public Criteria andCscSalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("csc_sal >=", value, "cscSal");
            return (Criteria) this;
        }

        public Criteria andCscSalLessThan(BigDecimal value) {
            addCriterion("csc_sal <", value, "cscSal");
            return (Criteria) this;
        }

        public Criteria andCscSalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("csc_sal <=", value, "cscSal");
            return (Criteria) this;
        }

        public Criteria andCscSalIn(List<BigDecimal> values) {
            addCriterion("csc_sal in", values, "cscSal");
            return (Criteria) this;
        }

        public Criteria andCscSalNotIn(List<BigDecimal> values) {
            addCriterion("csc_sal not in", values, "cscSal");
            return (Criteria) this;
        }

        public Criteria andCscSalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("csc_sal between", value1, value2, "cscSal");
            return (Criteria) this;
        }

        public Criteria andCscSalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("csc_sal not between", value1, value2, "cscSal");
            return (Criteria) this;
        }

        public Criteria andCscAddressIsNull() {
            addCriterion("csc_address is null");
            return (Criteria) this;
        }

        public Criteria andCscAddressIsNotNull() {
            addCriterion("csc_address is not null");
            return (Criteria) this;
        }

        public Criteria andCscAddressEqualTo(String value) {
            addCriterion("csc_address =", value, "cscAddress");
            return (Criteria) this;
        }

        public Criteria andCscAddressNotEqualTo(String value) {
            addCriterion("csc_address <>", value, "cscAddress");
            return (Criteria) this;
        }

        public Criteria andCscAddressGreaterThan(String value) {
            addCriterion("csc_address >", value, "cscAddress");
            return (Criteria) this;
        }

        public Criteria andCscAddressGreaterThanOrEqualTo(String value) {
            addCriterion("csc_address >=", value, "cscAddress");
            return (Criteria) this;
        }

        public Criteria andCscAddressLessThan(String value) {
            addCriterion("csc_address <", value, "cscAddress");
            return (Criteria) this;
        }

        public Criteria andCscAddressLessThanOrEqualTo(String value) {
            addCriterion("csc_address <=", value, "cscAddress");
            return (Criteria) this;
        }

        public Criteria andCscAddressLike(String value) {
            addCriterion("csc_address like", value, "cscAddress");
            return (Criteria) this;
        }

        public Criteria andCscAddressNotLike(String value) {
            addCriterion("csc_address not like", value, "cscAddress");
            return (Criteria) this;
        }

        public Criteria andCscAddressIn(List<String> values) {
            addCriterion("csc_address in", values, "cscAddress");
            return (Criteria) this;
        }

        public Criteria andCscAddressNotIn(List<String> values) {
            addCriterion("csc_address not in", values, "cscAddress");
            return (Criteria) this;
        }

        public Criteria andCscAddressBetween(String value1, String value2) {
            addCriterion("csc_address between", value1, value2, "cscAddress");
            return (Criteria) this;
        }

        public Criteria andCscAddressNotBetween(String value1, String value2) {
            addCriterion("csc_address not between", value1, value2, "cscAddress");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNull() {
            addCriterion("company is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("company is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEqualTo(Integer value) {
            addCriterion("company =", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotEqualTo(Integer value) {
            addCriterion("company <>", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThan(Integer value) {
            addCriterion("company >", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(Integer value) {
            addCriterion("company >=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThan(Integer value) {
            addCriterion("company <", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThanOrEqualTo(Integer value) {
            addCriterion("company <=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyIn(List<Integer> values) {
            addCriterion("company in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotIn(List<Integer> values) {
            addCriterion("company not in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyBetween(Integer value1, Integer value2) {
            addCriterion("company between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotBetween(Integer value1, Integer value2) {
            addCriterion("company not between", value1, value2, "company");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table constructionman
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 19:23:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table constructionman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}