package com.woniuxy.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class CranemanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public CranemanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCmIdIsNull() {
            addCriterion("cm_id is null");
            return (Criteria) this;
        }

        public Criteria andCmIdIsNotNull() {
            addCriterion("cm_id is not null");
            return (Criteria) this;
        }

        public Criteria andCmIdEqualTo(Integer value) {
            addCriterion("cm_id =", value, "cmId");
            return (Criteria) this;
        }

        public Criteria andCmIdNotEqualTo(Integer value) {
            addCriterion("cm_id <>", value, "cmId");
            return (Criteria) this;
        }

        public Criteria andCmIdGreaterThan(Integer value) {
            addCriterion("cm_id >", value, "cmId");
            return (Criteria) this;
        }

        public Criteria andCmIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cm_id >=", value, "cmId");
            return (Criteria) this;
        }

        public Criteria andCmIdLessThan(Integer value) {
            addCriterion("cm_id <", value, "cmId");
            return (Criteria) this;
        }

        public Criteria andCmIdLessThanOrEqualTo(Integer value) {
            addCriterion("cm_id <=", value, "cmId");
            return (Criteria) this;
        }

        public Criteria andCmIdIn(List<Integer> values) {
            addCriterion("cm_id in", values, "cmId");
            return (Criteria) this;
        }

        public Criteria andCmIdNotIn(List<Integer> values) {
            addCriterion("cm_id not in", values, "cmId");
            return (Criteria) this;
        }

        public Criteria andCmIdBetween(Integer value1, Integer value2) {
            addCriterion("cm_id between", value1, value2, "cmId");
            return (Criteria) this;
        }

        public Criteria andCmIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cm_id not between", value1, value2, "cmId");
            return (Criteria) this;
        }

        public Criteria andCmNameIsNull() {
            addCriterion("cm_name is null");
            return (Criteria) this;
        }

        public Criteria andCmNameIsNotNull() {
            addCriterion("cm_name is not null");
            return (Criteria) this;
        }

        public Criteria andCmNameEqualTo(String value) {
            addCriterion("cm_name =", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameNotEqualTo(String value) {
            addCriterion("cm_name <>", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameGreaterThan(String value) {
            addCriterion("cm_name >", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameGreaterThanOrEqualTo(String value) {
            addCriterion("cm_name >=", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameLessThan(String value) {
            addCriterion("cm_name <", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameLessThanOrEqualTo(String value) {
            addCriterion("cm_name <=", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameLike(String value) {
            addCriterion("cm_name like", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameNotLike(String value) {
            addCriterion("cm_name not like", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameIn(List<String> values) {
            addCriterion("cm_name in", values, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameNotIn(List<String> values) {
            addCriterion("cm_name not in", values, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameBetween(String value1, String value2) {
            addCriterion("cm_name between", value1, value2, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameNotBetween(String value1, String value2) {
            addCriterion("cm_name not between", value1, value2, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmSexIsNull() {
            addCriterion("cm_sex is null");
            return (Criteria) this;
        }

        public Criteria andCmSexIsNotNull() {
            addCriterion("cm_sex is not null");
            return (Criteria) this;
        }

        public Criteria andCmSexEqualTo(String value) {
            addCriterion("cm_sex =", value, "cmSex");
            return (Criteria) this;
        }

        public Criteria andCmSexNotEqualTo(String value) {
            addCriterion("cm_sex <>", value, "cmSex");
            return (Criteria) this;
        }

        public Criteria andCmSexGreaterThan(String value) {
            addCriterion("cm_sex >", value, "cmSex");
            return (Criteria) this;
        }

        public Criteria andCmSexGreaterThanOrEqualTo(String value) {
            addCriterion("cm_sex >=", value, "cmSex");
            return (Criteria) this;
        }

        public Criteria andCmSexLessThan(String value) {
            addCriterion("cm_sex <", value, "cmSex");
            return (Criteria) this;
        }

        public Criteria andCmSexLessThanOrEqualTo(String value) {
            addCriterion("cm_sex <=", value, "cmSex");
            return (Criteria) this;
        }

        public Criteria andCmSexLike(String value) {
            addCriterion("cm_sex like", value, "cmSex");
            return (Criteria) this;
        }

        public Criteria andCmSexNotLike(String value) {
            addCriterion("cm_sex not like", value, "cmSex");
            return (Criteria) this;
        }

        public Criteria andCmSexIn(List<String> values) {
            addCriterion("cm_sex in", values, "cmSex");
            return (Criteria) this;
        }

        public Criteria andCmSexNotIn(List<String> values) {
            addCriterion("cm_sex not in", values, "cmSex");
            return (Criteria) this;
        }

        public Criteria andCmSexBetween(String value1, String value2) {
            addCriterion("cm_sex between", value1, value2, "cmSex");
            return (Criteria) this;
        }

        public Criteria andCmSexNotBetween(String value1, String value2) {
            addCriterion("cm_sex not between", value1, value2, "cmSex");
            return (Criteria) this;
        }

        public Criteria andCmAgeIsNull() {
            addCriterion("cm_age is null");
            return (Criteria) this;
        }

        public Criteria andCmAgeIsNotNull() {
            addCriterion("cm_age is not null");
            return (Criteria) this;
        }

        public Criteria andCmAgeEqualTo(Integer value) {
            addCriterion("cm_age =", value, "cmAge");
            return (Criteria) this;
        }

        public Criteria andCmAgeNotEqualTo(Integer value) {
            addCriterion("cm_age <>", value, "cmAge");
            return (Criteria) this;
        }

        public Criteria andCmAgeGreaterThan(Integer value) {
            addCriterion("cm_age >", value, "cmAge");
            return (Criteria) this;
        }

        public Criteria andCmAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("cm_age >=", value, "cmAge");
            return (Criteria) this;
        }

        public Criteria andCmAgeLessThan(Integer value) {
            addCriterion("cm_age <", value, "cmAge");
            return (Criteria) this;
        }

        public Criteria andCmAgeLessThanOrEqualTo(Integer value) {
            addCriterion("cm_age <=", value, "cmAge");
            return (Criteria) this;
        }

        public Criteria andCmAgeIn(List<Integer> values) {
            addCriterion("cm_age in", values, "cmAge");
            return (Criteria) this;
        }

        public Criteria andCmAgeNotIn(List<Integer> values) {
            addCriterion("cm_age not in", values, "cmAge");
            return (Criteria) this;
        }

        public Criteria andCmAgeBetween(Integer value1, Integer value2) {
            addCriterion("cm_age between", value1, value2, "cmAge");
            return (Criteria) this;
        }

        public Criteria andCmAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("cm_age not between", value1, value2, "cmAge");
            return (Criteria) this;
        }

        public Criteria andCmPhoneIsNull() {
            addCriterion("cm_phone is null");
            return (Criteria) this;
        }

        public Criteria andCmPhoneIsNotNull() {
            addCriterion("cm_phone is not null");
            return (Criteria) this;
        }

        public Criteria andCmPhoneEqualTo(Integer value) {
            addCriterion("cm_phone =", value, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneNotEqualTo(Integer value) {
            addCriterion("cm_phone <>", value, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneGreaterThan(Integer value) {
            addCriterion("cm_phone >", value, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("cm_phone >=", value, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneLessThan(Integer value) {
            addCriterion("cm_phone <", value, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneLessThanOrEqualTo(Integer value) {
            addCriterion("cm_phone <=", value, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneIn(List<Integer> values) {
            addCriterion("cm_phone in", values, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneNotIn(List<Integer> values) {
            addCriterion("cm_phone not in", values, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneBetween(Integer value1, Integer value2) {
            addCriterion("cm_phone between", value1, value2, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneNotBetween(Integer value1, Integer value2) {
            addCriterion("cm_phone not between", value1, value2, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmSalIsNull() {
            addCriterion("cm_sal is null");
            return (Criteria) this;
        }

        public Criteria andCmSalIsNotNull() {
            addCriterion("cm_sal is not null");
            return (Criteria) this;
        }

        public Criteria andCmSalEqualTo(BigDecimal value) {
            addCriterion("cm_sal =", value, "cmSal");
            return (Criteria) this;
        }

        public Criteria andCmSalNotEqualTo(BigDecimal value) {
            addCriterion("cm_sal <>", value, "cmSal");
            return (Criteria) this;
        }

        public Criteria andCmSalGreaterThan(BigDecimal value) {
            addCriterion("cm_sal >", value, "cmSal");
            return (Criteria) this;
        }

        public Criteria andCmSalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cm_sal >=", value, "cmSal");
            return (Criteria) this;
        }

        public Criteria andCmSalLessThan(BigDecimal value) {
            addCriterion("cm_sal <", value, "cmSal");
            return (Criteria) this;
        }

        public Criteria andCmSalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cm_sal <=", value, "cmSal");
            return (Criteria) this;
        }

        public Criteria andCmSalIn(List<BigDecimal> values) {
            addCriterion("cm_sal in", values, "cmSal");
            return (Criteria) this;
        }

        public Criteria andCmSalNotIn(List<BigDecimal> values) {
            addCriterion("cm_sal not in", values, "cmSal");
            return (Criteria) this;
        }

        public Criteria andCmSalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cm_sal between", value1, value2, "cmSal");
            return (Criteria) this;
        }

        public Criteria andCmSalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cm_sal not between", value1, value2, "cmSal");
            return (Criteria) this;
        }

        public Criteria andCmAddressIsNull() {
            addCriterion("cm_address is null");
            return (Criteria) this;
        }

        public Criteria andCmAddressIsNotNull() {
            addCriterion("cm_address is not null");
            return (Criteria) this;
        }

        public Criteria andCmAddressEqualTo(String value) {
            addCriterion("cm_address =", value, "cmAddress");
            return (Criteria) this;
        }

        public Criteria andCmAddressNotEqualTo(String value) {
            addCriterion("cm_address <>", value, "cmAddress");
            return (Criteria) this;
        }

        public Criteria andCmAddressGreaterThan(String value) {
            addCriterion("cm_address >", value, "cmAddress");
            return (Criteria) this;
        }

        public Criteria andCmAddressGreaterThanOrEqualTo(String value) {
            addCriterion("cm_address >=", value, "cmAddress");
            return (Criteria) this;
        }

        public Criteria andCmAddressLessThan(String value) {
            addCriterion("cm_address <", value, "cmAddress");
            return (Criteria) this;
        }

        public Criteria andCmAddressLessThanOrEqualTo(String value) {
            addCriterion("cm_address <=", value, "cmAddress");
            return (Criteria) this;
        }

        public Criteria andCmAddressLike(String value) {
            addCriterion("cm_address like", value, "cmAddress");
            return (Criteria) this;
        }

        public Criteria andCmAddressNotLike(String value) {
            addCriterion("cm_address not like", value, "cmAddress");
            return (Criteria) this;
        }

        public Criteria andCmAddressIn(List<String> values) {
            addCriterion("cm_address in", values, "cmAddress");
            return (Criteria) this;
        }

        public Criteria andCmAddressNotIn(List<String> values) {
            addCriterion("cm_address not in", values, "cmAddress");
            return (Criteria) this;
        }

        public Criteria andCmAddressBetween(String value1, String value2) {
            addCriterion("cm_address between", value1, value2, "cmAddress");
            return (Criteria) this;
        }

        public Criteria andCmAddressNotBetween(String value1, String value2) {
            addCriterion("cm_address not between", value1, value2, "cmAddress");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNull() {
            addCriterion("company is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("company is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEqualTo(Integer value) {
            addCriterion("company =", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotEqualTo(Integer value) {
            addCriterion("company <>", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThan(Integer value) {
            addCriterion("company >", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(Integer value) {
            addCriterion("company >=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThan(Integer value) {
            addCriterion("company <", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThanOrEqualTo(Integer value) {
            addCriterion("company <=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyIn(List<Integer> values) {
            addCriterion("company in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotIn(List<Integer> values) {
            addCriterion("company not in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyBetween(Integer value1, Integer value2) {
            addCriterion("company between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotBetween(Integer value1, Integer value2) {
            addCriterion("company not between", value1, value2, "company");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table craneman
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 19:23:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table craneman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}