package com.woniuxy.entity;

public class EmbedmentStockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embedment_stock.p3_eid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer p3Eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embedment_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embedment_stock.p3_eid
     *
     * @return the value of embedment_stock.p3_eid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getP3Eid() {
        return p3Eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embedment_stock.p3_eid
     *
     * @param p3Eid the value for embedment_stock.p3_eid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP3Eid(Integer p3Eid) {
        this.p3Eid = p3Eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embedment_stock.sid
     *
     * @return the value of embedment_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embedment_stock.sid
     *
     * @param sid the value for embedment_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }
}