package com.woniuxy.entity;

public class Embedment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embedment.p3_eid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer p3Eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embedment.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embedment.p3_ename
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p3Ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embedment.p3_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p3Status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embedment.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embedment.p3_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p3Remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embedment.p3_eid
     *
     * @return the value of embedment.p3_eid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getP3Eid() {
        return p3Eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embedment.p3_eid
     *
     * @param p3Eid the value for embedment.p3_eid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP3Eid(Integer p3Eid) {
        this.p3Eid = p3Eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embedment.project_id
     *
     * @return the value of embedment.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embedment.project_id
     *
     * @param projectId the value for embedment.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embedment.p3_ename
     *
     * @return the value of embedment.p3_ename
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP3Ename() {
        return p3Ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embedment.p3_ename
     *
     * @param p3Ename the value for embedment.p3_ename
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP3Ename(String p3Ename) {
        this.p3Ename = p3Ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embedment.p3_status
     *
     * @return the value of embedment.p3_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP3Status() {
        return p3Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embedment.p3_status
     *
     * @param p3Status the value for embedment.p3_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP3Status(String p3Status) {
        this.p3Status = p3Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embedment.company
     *
     * @return the value of embedment.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embedment.company
     *
     * @param company the value for embedment.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embedment.p3_remarks
     *
     * @return the value of embedment.p3_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP3Remarks() {
        return p3Remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embedment.p3_remarks
     *
     * @param p3Remarks the value for embedment.p3_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP3Remarks(String p3Remarks) {
        this.p3Remarks = p3Remarks;
    }
}