package com.woniuxy.entity;

import java.util.ArrayList;
import java.util.List;

public class EmbedmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public EmbedmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andP3EidIsNull() {
            addCriterion("p3_eid is null");
            return (Criteria) this;
        }

        public Criteria andP3EidIsNotNull() {
            addCriterion("p3_eid is not null");
            return (Criteria) this;
        }

        public Criteria andP3EidEqualTo(Integer value) {
            addCriterion("p3_eid =", value, "p3Eid");
            return (Criteria) this;
        }

        public Criteria andP3EidNotEqualTo(Integer value) {
            addCriterion("p3_eid <>", value, "p3Eid");
            return (Criteria) this;
        }

        public Criteria andP3EidGreaterThan(Integer value) {
            addCriterion("p3_eid >", value, "p3Eid");
            return (Criteria) this;
        }

        public Criteria andP3EidGreaterThanOrEqualTo(Integer value) {
            addCriterion("p3_eid >=", value, "p3Eid");
            return (Criteria) this;
        }

        public Criteria andP3EidLessThan(Integer value) {
            addCriterion("p3_eid <", value, "p3Eid");
            return (Criteria) this;
        }

        public Criteria andP3EidLessThanOrEqualTo(Integer value) {
            addCriterion("p3_eid <=", value, "p3Eid");
            return (Criteria) this;
        }

        public Criteria andP3EidIn(List<Integer> values) {
            addCriterion("p3_eid in", values, "p3Eid");
            return (Criteria) this;
        }

        public Criteria andP3EidNotIn(List<Integer> values) {
            addCriterion("p3_eid not in", values, "p3Eid");
            return (Criteria) this;
        }

        public Criteria andP3EidBetween(Integer value1, Integer value2) {
            addCriterion("p3_eid between", value1, value2, "p3Eid");
            return (Criteria) this;
        }

        public Criteria andP3EidNotBetween(Integer value1, Integer value2) {
            addCriterion("p3_eid not between", value1, value2, "p3Eid");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andP3EnameIsNull() {
            addCriterion("p3_ename is null");
            return (Criteria) this;
        }

        public Criteria andP3EnameIsNotNull() {
            addCriterion("p3_ename is not null");
            return (Criteria) this;
        }

        public Criteria andP3EnameEqualTo(String value) {
            addCriterion("p3_ename =", value, "p3Ename");
            return (Criteria) this;
        }

        public Criteria andP3EnameNotEqualTo(String value) {
            addCriterion("p3_ename <>", value, "p3Ename");
            return (Criteria) this;
        }

        public Criteria andP3EnameGreaterThan(String value) {
            addCriterion("p3_ename >", value, "p3Ename");
            return (Criteria) this;
        }

        public Criteria andP3EnameGreaterThanOrEqualTo(String value) {
            addCriterion("p3_ename >=", value, "p3Ename");
            return (Criteria) this;
        }

        public Criteria andP3EnameLessThan(String value) {
            addCriterion("p3_ename <", value, "p3Ename");
            return (Criteria) this;
        }

        public Criteria andP3EnameLessThanOrEqualTo(String value) {
            addCriterion("p3_ename <=", value, "p3Ename");
            return (Criteria) this;
        }

        public Criteria andP3EnameLike(String value) {
            addCriterion("p3_ename like", value, "p3Ename");
            return (Criteria) this;
        }

        public Criteria andP3EnameNotLike(String value) {
            addCriterion("p3_ename not like", value, "p3Ename");
            return (Criteria) this;
        }

        public Criteria andP3EnameIn(List<String> values) {
            addCriterion("p3_ename in", values, "p3Ename");
            return (Criteria) this;
        }

        public Criteria andP3EnameNotIn(List<String> values) {
            addCriterion("p3_ename not in", values, "p3Ename");
            return (Criteria) this;
        }

        public Criteria andP3EnameBetween(String value1, String value2) {
            addCriterion("p3_ename between", value1, value2, "p3Ename");
            return (Criteria) this;
        }

        public Criteria andP3EnameNotBetween(String value1, String value2) {
            addCriterion("p3_ename not between", value1, value2, "p3Ename");
            return (Criteria) this;
        }

        public Criteria andP3StatusIsNull() {
            addCriterion("p3_status is null");
            return (Criteria) this;
        }

        public Criteria andP3StatusIsNotNull() {
            addCriterion("p3_status is not null");
            return (Criteria) this;
        }

        public Criteria andP3StatusEqualTo(String value) {
            addCriterion("p3_status =", value, "p3Status");
            return (Criteria) this;
        }

        public Criteria andP3StatusNotEqualTo(String value) {
            addCriterion("p3_status <>", value, "p3Status");
            return (Criteria) this;
        }

        public Criteria andP3StatusGreaterThan(String value) {
            addCriterion("p3_status >", value, "p3Status");
            return (Criteria) this;
        }

        public Criteria andP3StatusGreaterThanOrEqualTo(String value) {
            addCriterion("p3_status >=", value, "p3Status");
            return (Criteria) this;
        }

        public Criteria andP3StatusLessThan(String value) {
            addCriterion("p3_status <", value, "p3Status");
            return (Criteria) this;
        }

        public Criteria andP3StatusLessThanOrEqualTo(String value) {
            addCriterion("p3_status <=", value, "p3Status");
            return (Criteria) this;
        }

        public Criteria andP3StatusLike(String value) {
            addCriterion("p3_status like", value, "p3Status");
            return (Criteria) this;
        }

        public Criteria andP3StatusNotLike(String value) {
            addCriterion("p3_status not like", value, "p3Status");
            return (Criteria) this;
        }

        public Criteria andP3StatusIn(List<String> values) {
            addCriterion("p3_status in", values, "p3Status");
            return (Criteria) this;
        }

        public Criteria andP3StatusNotIn(List<String> values) {
            addCriterion("p3_status not in", values, "p3Status");
            return (Criteria) this;
        }

        public Criteria andP3StatusBetween(String value1, String value2) {
            addCriterion("p3_status between", value1, value2, "p3Status");
            return (Criteria) this;
        }

        public Criteria andP3StatusNotBetween(String value1, String value2) {
            addCriterion("p3_status not between", value1, value2, "p3Status");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNull() {
            addCriterion("company is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("company is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEqualTo(Integer value) {
            addCriterion("company =", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotEqualTo(Integer value) {
            addCriterion("company <>", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThan(Integer value) {
            addCriterion("company >", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(Integer value) {
            addCriterion("company >=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThan(Integer value) {
            addCriterion("company <", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThanOrEqualTo(Integer value) {
            addCriterion("company <=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyIn(List<Integer> values) {
            addCriterion("company in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotIn(List<Integer> values) {
            addCriterion("company not in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyBetween(Integer value1, Integer value2) {
            addCriterion("company between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotBetween(Integer value1, Integer value2) {
            addCriterion("company not between", value1, value2, "company");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table embedment
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 19:23:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table embedment
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}