package com.woniuxy.entity;

import java.math.BigDecimal;

public class Foreman {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.fm_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer fmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.fm_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String fmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.fm_sex
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String fmSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.fm_age
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer fmAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.fm_phone
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer fmPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.fm_sal
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private BigDecimal fmSal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.fm_address
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String fmAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.fm_id
     *
     * @return the value of foreman.fm_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getFmId() {
        return fmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.fm_id
     *
     * @param fmId the value for foreman.fm_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setFmId(Integer fmId) {
        this.fmId = fmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.fm_name
     *
     * @return the value of foreman.fm_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getFmName() {
        return fmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.fm_name
     *
     * @param fmName the value for foreman.fm_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setFmName(String fmName) {
        this.fmName = fmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.fm_sex
     *
     * @return the value of foreman.fm_sex
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getFmSex() {
        return fmSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.fm_sex
     *
     * @param fmSex the value for foreman.fm_sex
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setFmSex(String fmSex) {
        this.fmSex = fmSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.fm_age
     *
     * @return the value of foreman.fm_age
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getFmAge() {
        return fmAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.fm_age
     *
     * @param fmAge the value for foreman.fm_age
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setFmAge(Integer fmAge) {
        this.fmAge = fmAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.fm_phone
     *
     * @return the value of foreman.fm_phone
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getFmPhone() {
        return fmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.fm_phone
     *
     * @param fmPhone the value for foreman.fm_phone
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setFmPhone(Integer fmPhone) {
        this.fmPhone = fmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.fm_sal
     *
     * @return the value of foreman.fm_sal
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public BigDecimal getFmSal() {
        return fmSal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.fm_sal
     *
     * @param fmSal the value for foreman.fm_sal
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setFmSal(BigDecimal fmSal) {
        this.fmSal = fmSal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.fm_address
     *
     * @return the value of foreman.fm_address
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getFmAddress() {
        return fmAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.fm_address
     *
     * @param fmAddress the value for foreman.fm_address
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setFmAddress(String fmAddress) {
        this.fmAddress = fmAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.status
     *
     * @return the value of foreman.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.status
     *
     * @param status the value for foreman.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.company
     *
     * @return the value of foreman.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.company
     *
     * @param company the value for foreman.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }
}