package com.woniuxy.entity;

import java.math.BigDecimal;

public class General {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.project_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.progress
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private BigDecimal progress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.project_id
     *
     * @return the value of general.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.project_id
     *
     * @param projectId the value for general.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.project_name
     *
     * @return the value of general.project_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.project_name
     *
     * @param projectName the value for general.project_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.progress
     *
     * @return the value of general.progress
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public BigDecimal getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.progress
     *
     * @param progress the value for general.progress
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setProgress(BigDecimal progress) {
        this.progress = progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.company
     *
     * @return the value of general.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.company
     *
     * @param company the value for general.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }
}