package com.woniuxy.entity;

public class PaintingStockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting_stock.p7_ptid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer p7Ptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting_stock.p7_ptid
     *
     * @return the value of painting_stock.p7_ptid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getP7Ptid() {
        return p7Ptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting_stock.p7_ptid
     *
     * @param p7Ptid the value for painting_stock.p7_ptid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP7Ptid(Integer p7Ptid) {
        this.p7Ptid = p7Ptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting_stock.sid
     *
     * @return the value of painting_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting_stock.sid
     *
     * @param sid the value for painting_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }
}