package com.woniuxy.entity;

import java.util.ArrayList;
import java.util.List;

public class PaintingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public PaintingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andP7PtidIsNull() {
            addCriterion("p7_ptid is null");
            return (Criteria) this;
        }

        public Criteria andP7PtidIsNotNull() {
            addCriterion("p7_ptid is not null");
            return (Criteria) this;
        }

        public Criteria andP7PtidEqualTo(Integer value) {
            addCriterion("p7_ptid =", value, "p7Ptid");
            return (Criteria) this;
        }

        public Criteria andP7PtidNotEqualTo(Integer value) {
            addCriterion("p7_ptid <>", value, "p7Ptid");
            return (Criteria) this;
        }

        public Criteria andP7PtidGreaterThan(Integer value) {
            addCriterion("p7_ptid >", value, "p7Ptid");
            return (Criteria) this;
        }

        public Criteria andP7PtidGreaterThanOrEqualTo(Integer value) {
            addCriterion("p7_ptid >=", value, "p7Ptid");
            return (Criteria) this;
        }

        public Criteria andP7PtidLessThan(Integer value) {
            addCriterion("p7_ptid <", value, "p7Ptid");
            return (Criteria) this;
        }

        public Criteria andP7PtidLessThanOrEqualTo(Integer value) {
            addCriterion("p7_ptid <=", value, "p7Ptid");
            return (Criteria) this;
        }

        public Criteria andP7PtidIn(List<Integer> values) {
            addCriterion("p7_ptid in", values, "p7Ptid");
            return (Criteria) this;
        }

        public Criteria andP7PtidNotIn(List<Integer> values) {
            addCriterion("p7_ptid not in", values, "p7Ptid");
            return (Criteria) this;
        }

        public Criteria andP7PtidBetween(Integer value1, Integer value2) {
            addCriterion("p7_ptid between", value1, value2, "p7Ptid");
            return (Criteria) this;
        }

        public Criteria andP7PtidNotBetween(Integer value1, Integer value2) {
            addCriterion("p7_ptid not between", value1, value2, "p7Ptid");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andP7PtnameIsNull() {
            addCriterion("p7_ptname is null");
            return (Criteria) this;
        }

        public Criteria andP7PtnameIsNotNull() {
            addCriterion("p7_ptname is not null");
            return (Criteria) this;
        }

        public Criteria andP7PtnameEqualTo(String value) {
            addCriterion("p7_ptname =", value, "p7Ptname");
            return (Criteria) this;
        }

        public Criteria andP7PtnameNotEqualTo(String value) {
            addCriterion("p7_ptname <>", value, "p7Ptname");
            return (Criteria) this;
        }

        public Criteria andP7PtnameGreaterThan(String value) {
            addCriterion("p7_ptname >", value, "p7Ptname");
            return (Criteria) this;
        }

        public Criteria andP7PtnameGreaterThanOrEqualTo(String value) {
            addCriterion("p7_ptname >=", value, "p7Ptname");
            return (Criteria) this;
        }

        public Criteria andP7PtnameLessThan(String value) {
            addCriterion("p7_ptname <", value, "p7Ptname");
            return (Criteria) this;
        }

        public Criteria andP7PtnameLessThanOrEqualTo(String value) {
            addCriterion("p7_ptname <=", value, "p7Ptname");
            return (Criteria) this;
        }

        public Criteria andP7PtnameLike(String value) {
            addCriterion("p7_ptname like", value, "p7Ptname");
            return (Criteria) this;
        }

        public Criteria andP7PtnameNotLike(String value) {
            addCriterion("p7_ptname not like", value, "p7Ptname");
            return (Criteria) this;
        }

        public Criteria andP7PtnameIn(List<String> values) {
            addCriterion("p7_ptname in", values, "p7Ptname");
            return (Criteria) this;
        }

        public Criteria andP7PtnameNotIn(List<String> values) {
            addCriterion("p7_ptname not in", values, "p7Ptname");
            return (Criteria) this;
        }

        public Criteria andP7PtnameBetween(String value1, String value2) {
            addCriterion("p7_ptname between", value1, value2, "p7Ptname");
            return (Criteria) this;
        }

        public Criteria andP7PtnameNotBetween(String value1, String value2) {
            addCriterion("p7_ptname not between", value1, value2, "p7Ptname");
            return (Criteria) this;
        }

        public Criteria andP7StatusIsNull() {
            addCriterion("p7_status is null");
            return (Criteria) this;
        }

        public Criteria andP7StatusIsNotNull() {
            addCriterion("p7_status is not null");
            return (Criteria) this;
        }

        public Criteria andP7StatusEqualTo(String value) {
            addCriterion("p7_status =", value, "p7Status");
            return (Criteria) this;
        }

        public Criteria andP7StatusNotEqualTo(String value) {
            addCriterion("p7_status <>", value, "p7Status");
            return (Criteria) this;
        }

        public Criteria andP7StatusGreaterThan(String value) {
            addCriterion("p7_status >", value, "p7Status");
            return (Criteria) this;
        }

        public Criteria andP7StatusGreaterThanOrEqualTo(String value) {
            addCriterion("p7_status >=", value, "p7Status");
            return (Criteria) this;
        }

        public Criteria andP7StatusLessThan(String value) {
            addCriterion("p7_status <", value, "p7Status");
            return (Criteria) this;
        }

        public Criteria andP7StatusLessThanOrEqualTo(String value) {
            addCriterion("p7_status <=", value, "p7Status");
            return (Criteria) this;
        }

        public Criteria andP7StatusLike(String value) {
            addCriterion("p7_status like", value, "p7Status");
            return (Criteria) this;
        }

        public Criteria andP7StatusNotLike(String value) {
            addCriterion("p7_status not like", value, "p7Status");
            return (Criteria) this;
        }

        public Criteria andP7StatusIn(List<String> values) {
            addCriterion("p7_status in", values, "p7Status");
            return (Criteria) this;
        }

        public Criteria andP7StatusNotIn(List<String> values) {
            addCriterion("p7_status not in", values, "p7Status");
            return (Criteria) this;
        }

        public Criteria andP7StatusBetween(String value1, String value2) {
            addCriterion("p7_status between", value1, value2, "p7Status");
            return (Criteria) this;
        }

        public Criteria andP7StatusNotBetween(String value1, String value2) {
            addCriterion("p7_status not between", value1, value2, "p7Status");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNull() {
            addCriterion("company is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("company is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEqualTo(Integer value) {
            addCriterion("company =", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotEqualTo(Integer value) {
            addCriterion("company <>", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThan(Integer value) {
            addCriterion("company >", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(Integer value) {
            addCriterion("company >=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThan(Integer value) {
            addCriterion("company <", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThanOrEqualTo(Integer value) {
            addCriterion("company <=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyIn(List<Integer> values) {
            addCriterion("company in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotIn(List<Integer> values) {
            addCriterion("company not in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyBetween(Integer value1, Integer value2) {
            addCriterion("company between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotBetween(Integer value1, Integer value2) {
            addCriterion("company not between", value1, value2, "company");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table painting
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 19:23:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table painting
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}