package com.woniuxy.entity;

public class Painting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.p7_ptid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer p7Ptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.p7_ptname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p7Ptname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.p7_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p7Status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.p7_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p7Remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.p7_ptid
     *
     * @return the value of painting.p7_ptid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getP7Ptid() {
        return p7Ptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.p7_ptid
     *
     * @param p7Ptid the value for painting.p7_ptid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP7Ptid(Integer p7Ptid) {
        this.p7Ptid = p7Ptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.project_id
     *
     * @return the value of painting.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.project_id
     *
     * @param projectId the value for painting.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.p7_ptname
     *
     * @return the value of painting.p7_ptname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP7Ptname() {
        return p7Ptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.p7_ptname
     *
     * @param p7Ptname the value for painting.p7_ptname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP7Ptname(String p7Ptname) {
        this.p7Ptname = p7Ptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.p7_status
     *
     * @return the value of painting.p7_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP7Status() {
        return p7Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.p7_status
     *
     * @param p7Status the value for painting.p7_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP7Status(String p7Status) {
        this.p7Status = p7Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.company
     *
     * @return the value of painting.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.company
     *
     * @param company the value for painting.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.p7_remarks
     *
     * @return the value of painting.p7_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP7Remarks() {
        return p7Remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.p7_remarks
     *
     * @param p7Remarks the value for painting.p7_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP7Remarks(String p7Remarks) {
        this.p7Remarks = p7Remarks;
    }
}