package com.woniuxy.entity;

public class Party {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.companyname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.company
     *
     * @return the value of party.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.company
     *
     * @param company the value for party.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.companyname
     *
     * @return the value of party.companyname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.companyname
     *
     * @param companyname the value for party.companyname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.status
     *
     * @return the value of party.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.status
     *
     * @param status the value for party.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}