package com.woniuxy.entity;

public class Pit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pit.p2_pid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer p2Pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pit.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pit.p2_pname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p2Pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pit.p2_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p2Status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pit.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pit.p2_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p2Remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pit.p2_pid
     *
     * @return the value of pit.p2_pid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getP2Pid() {
        return p2Pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pit.p2_pid
     *
     * @param p2Pid the value for pit.p2_pid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP2Pid(Integer p2Pid) {
        this.p2Pid = p2Pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pit.project_id
     *
     * @return the value of pit.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pit.project_id
     *
     * @param projectId the value for pit.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pit.p2_pname
     *
     * @return the value of pit.p2_pname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP2Pname() {
        return p2Pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pit.p2_pname
     *
     * @param p2Pname the value for pit.p2_pname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP2Pname(String p2Pname) {
        this.p2Pname = p2Pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pit.p2_status
     *
     * @return the value of pit.p2_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP2Status() {
        return p2Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pit.p2_status
     *
     * @param p2Status the value for pit.p2_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP2Status(String p2Status) {
        this.p2Status = p2Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pit.company
     *
     * @return the value of pit.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pit.company
     *
     * @param company the value for pit.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pit.p2_remarks
     *
     * @return the value of pit.p2_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP2Remarks() {
        return p2Remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pit.p2_remarks
     *
     * @param p2Remarks the value for pit.p2_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP2Remarks(String p2Remarks) {
        this.p2Remarks = p2Remarks;
    }
}