package com.woniuxy.entity;

public class PitStockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pit_stock.p2_pid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer p2Pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pit_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pit_stock.p2_pid
     *
     * @return the value of pit_stock.p2_pid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getP2Pid() {
        return p2Pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pit_stock.p2_pid
     *
     * @param p2Pid the value for pit_stock.p2_pid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP2Pid(Integer p2Pid) {
        this.p2Pid = p2Pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pit_stock.sid
     *
     * @return the value of pit_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pit_stock.sid
     *
     * @param sid the value for pit_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }
}