package com.woniuxy.entity;

public class Process {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.sname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.nowCount
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer nowcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.overCount
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer overcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.sid
     *
     * @return the value of process.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.sid
     *
     * @param sid the value for process.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.sname
     *
     * @return the value of process.sname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.sname
     *
     * @param sname the value for process.sname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.nowCount
     *
     * @return the value of process.nowCount
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getNowcount() {
        return nowcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.nowCount
     *
     * @param nowcount the value for process.nowCount
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setNowcount(Integer nowcount) {
        this.nowcount = nowcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.overCount
     *
     * @return the value of process.overCount
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getOvercount() {
        return overcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.overCount
     *
     * @param overcount the value for process.overCount
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setOvercount(Integer overcount) {
        this.overcount = overcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.company
     *
     * @return the value of process.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.company
     *
     * @param company the value for process.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }
}