package com.woniuxy.entity;

import java.math.BigDecimal;

public class Projectman {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectman.pm_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer pmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectman.pm_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String pmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectman.pm_sex
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String pmSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectman.pm_age
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer pmAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectman.pm_phone
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer pmPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectman.pm_sal
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private BigDecimal pmSal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectman.pm_address
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String pmAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectman.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectman.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectman.pm_id
     *
     * @return the value of projectman.pm_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getPmId() {
        return pmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectman.pm_id
     *
     * @param pmId the value for projectman.pm_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setPmId(Integer pmId) {
        this.pmId = pmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectman.pm_name
     *
     * @return the value of projectman.pm_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getPmName() {
        return pmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectman.pm_name
     *
     * @param pmName the value for projectman.pm_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setPmName(String pmName) {
        this.pmName = pmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectman.pm_sex
     *
     * @return the value of projectman.pm_sex
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getPmSex() {
        return pmSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectman.pm_sex
     *
     * @param pmSex the value for projectman.pm_sex
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setPmSex(String pmSex) {
        this.pmSex = pmSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectman.pm_age
     *
     * @return the value of projectman.pm_age
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getPmAge() {
        return pmAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectman.pm_age
     *
     * @param pmAge the value for projectman.pm_age
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setPmAge(Integer pmAge) {
        this.pmAge = pmAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectman.pm_phone
     *
     * @return the value of projectman.pm_phone
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getPmPhone() {
        return pmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectman.pm_phone
     *
     * @param pmPhone the value for projectman.pm_phone
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setPmPhone(Integer pmPhone) {
        this.pmPhone = pmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectman.pm_sal
     *
     * @return the value of projectman.pm_sal
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public BigDecimal getPmSal() {
        return pmSal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectman.pm_sal
     *
     * @param pmSal the value for projectman.pm_sal
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setPmSal(BigDecimal pmSal) {
        this.pmSal = pmSal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectman.pm_address
     *
     * @return the value of projectman.pm_address
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getPmAddress() {
        return pmAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectman.pm_address
     *
     * @param pmAddress the value for projectman.pm_address
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setPmAddress(String pmAddress) {
        this.pmAddress = pmAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectman.status
     *
     * @return the value of projectman.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectman.status
     *
     * @param status the value for projectman.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectman.company
     *
     * @return the value of projectman.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectman.company
     *
     * @param company the value for projectman.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }

	@Override
	public String toString() {
		return "Projectman [pmId=" + pmId + ", pmName=" + pmName + ", pmSex=" + pmSex + ", pmAge=" + pmAge
				+ ", pmPhone=" + pmPhone + ", pmSal=" + pmSal + ", pmAddress=" + pmAddress + ", status=" + status
				+ ", company=" + company + "]";
	}
    
}