package com.woniuxy.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ProjectmanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public ProjectmanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPmIdIsNull() {
            addCriterion("pm_id is null");
            return (Criteria) this;
        }

        public Criteria andPmIdIsNotNull() {
            addCriterion("pm_id is not null");
            return (Criteria) this;
        }

        public Criteria andPmIdEqualTo(Integer value) {
            addCriterion("pm_id =", value, "pmId");
            return (Criteria) this;
        }

        public Criteria andPmIdNotEqualTo(Integer value) {
            addCriterion("pm_id <>", value, "pmId");
            return (Criteria) this;
        }

        public Criteria andPmIdGreaterThan(Integer value) {
            addCriterion("pm_id >", value, "pmId");
            return (Criteria) this;
        }

        public Criteria andPmIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pm_id >=", value, "pmId");
            return (Criteria) this;
        }

        public Criteria andPmIdLessThan(Integer value) {
            addCriterion("pm_id <", value, "pmId");
            return (Criteria) this;
        }

        public Criteria andPmIdLessThanOrEqualTo(Integer value) {
            addCriterion("pm_id <=", value, "pmId");
            return (Criteria) this;
        }

        public Criteria andPmIdIn(List<Integer> values) {
            addCriterion("pm_id in", values, "pmId");
            return (Criteria) this;
        }

        public Criteria andPmIdNotIn(List<Integer> values) {
            addCriterion("pm_id not in", values, "pmId");
            return (Criteria) this;
        }

        public Criteria andPmIdBetween(Integer value1, Integer value2) {
            addCriterion("pm_id between", value1, value2, "pmId");
            return (Criteria) this;
        }

        public Criteria andPmIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pm_id not between", value1, value2, "pmId");
            return (Criteria) this;
        }

        public Criteria andPmNameIsNull() {
            addCriterion("pm_name is null");
            return (Criteria) this;
        }

        public Criteria andPmNameIsNotNull() {
            addCriterion("pm_name is not null");
            return (Criteria) this;
        }

        public Criteria andPmNameEqualTo(String value) {
            addCriterion("pm_name =", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameNotEqualTo(String value) {
            addCriterion("pm_name <>", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameGreaterThan(String value) {
            addCriterion("pm_name >", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameGreaterThanOrEqualTo(String value) {
            addCriterion("pm_name >=", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameLessThan(String value) {
            addCriterion("pm_name <", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameLessThanOrEqualTo(String value) {
            addCriterion("pm_name <=", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameLike(String value) {
            addCriterion("pm_name like", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameNotLike(String value) {
            addCriterion("pm_name not like", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameIn(List<String> values) {
            addCriterion("pm_name in", values, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameNotIn(List<String> values) {
            addCriterion("pm_name not in", values, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameBetween(String value1, String value2) {
            addCriterion("pm_name between", value1, value2, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameNotBetween(String value1, String value2) {
            addCriterion("pm_name not between", value1, value2, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmSexIsNull() {
            addCriterion("pm_sex is null");
            return (Criteria) this;
        }

        public Criteria andPmSexIsNotNull() {
            addCriterion("pm_sex is not null");
            return (Criteria) this;
        }

        public Criteria andPmSexEqualTo(String value) {
            addCriterion("pm_sex =", value, "pmSex");
            return (Criteria) this;
        }

        public Criteria andPmSexNotEqualTo(String value) {
            addCriterion("pm_sex <>", value, "pmSex");
            return (Criteria) this;
        }

        public Criteria andPmSexGreaterThan(String value) {
            addCriterion("pm_sex >", value, "pmSex");
            return (Criteria) this;
        }

        public Criteria andPmSexGreaterThanOrEqualTo(String value) {
            addCriterion("pm_sex >=", value, "pmSex");
            return (Criteria) this;
        }

        public Criteria andPmSexLessThan(String value) {
            addCriterion("pm_sex <", value, "pmSex");
            return (Criteria) this;
        }

        public Criteria andPmSexLessThanOrEqualTo(String value) {
            addCriterion("pm_sex <=", value, "pmSex");
            return (Criteria) this;
        }

        public Criteria andPmSexLike(String value) {
            addCriterion("pm_sex like", value, "pmSex");
            return (Criteria) this;
        }

        public Criteria andPmSexNotLike(String value) {
            addCriterion("pm_sex not like", value, "pmSex");
            return (Criteria) this;
        }

        public Criteria andPmSexIn(List<String> values) {
            addCriterion("pm_sex in", values, "pmSex");
            return (Criteria) this;
        }

        public Criteria andPmSexNotIn(List<String> values) {
            addCriterion("pm_sex not in", values, "pmSex");
            return (Criteria) this;
        }

        public Criteria andPmSexBetween(String value1, String value2) {
            addCriterion("pm_sex between", value1, value2, "pmSex");
            return (Criteria) this;
        }

        public Criteria andPmSexNotBetween(String value1, String value2) {
            addCriterion("pm_sex not between", value1, value2, "pmSex");
            return (Criteria) this;
        }

        public Criteria andPmAgeIsNull() {
            addCriterion("pm_age is null");
            return (Criteria) this;
        }

        public Criteria andPmAgeIsNotNull() {
            addCriterion("pm_age is not null");
            return (Criteria) this;
        }

        public Criteria andPmAgeEqualTo(Integer value) {
            addCriterion("pm_age =", value, "pmAge");
            return (Criteria) this;
        }

        public Criteria andPmAgeNotEqualTo(Integer value) {
            addCriterion("pm_age <>", value, "pmAge");
            return (Criteria) this;
        }

        public Criteria andPmAgeGreaterThan(Integer value) {
            addCriterion("pm_age >", value, "pmAge");
            return (Criteria) this;
        }

        public Criteria andPmAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("pm_age >=", value, "pmAge");
            return (Criteria) this;
        }

        public Criteria andPmAgeLessThan(Integer value) {
            addCriterion("pm_age <", value, "pmAge");
            return (Criteria) this;
        }

        public Criteria andPmAgeLessThanOrEqualTo(Integer value) {
            addCriterion("pm_age <=", value, "pmAge");
            return (Criteria) this;
        }

        public Criteria andPmAgeIn(List<Integer> values) {
            addCriterion("pm_age in", values, "pmAge");
            return (Criteria) this;
        }

        public Criteria andPmAgeNotIn(List<Integer> values) {
            addCriterion("pm_age not in", values, "pmAge");
            return (Criteria) this;
        }

        public Criteria andPmAgeBetween(Integer value1, Integer value2) {
            addCriterion("pm_age between", value1, value2, "pmAge");
            return (Criteria) this;
        }

        public Criteria andPmAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("pm_age not between", value1, value2, "pmAge");
            return (Criteria) this;
        }

        public Criteria andPmPhoneIsNull() {
            addCriterion("pm_phone is null");
            return (Criteria) this;
        }

        public Criteria andPmPhoneIsNotNull() {
            addCriterion("pm_phone is not null");
            return (Criteria) this;
        }

        public Criteria andPmPhoneEqualTo(Integer value) {
            addCriterion("pm_phone =", value, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneNotEqualTo(Integer value) {
            addCriterion("pm_phone <>", value, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneGreaterThan(Integer value) {
            addCriterion("pm_phone >", value, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("pm_phone >=", value, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneLessThan(Integer value) {
            addCriterion("pm_phone <", value, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneLessThanOrEqualTo(Integer value) {
            addCriterion("pm_phone <=", value, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneIn(List<Integer> values) {
            addCriterion("pm_phone in", values, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneNotIn(List<Integer> values) {
            addCriterion("pm_phone not in", values, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneBetween(Integer value1, Integer value2) {
            addCriterion("pm_phone between", value1, value2, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneNotBetween(Integer value1, Integer value2) {
            addCriterion("pm_phone not between", value1, value2, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmSalIsNull() {
            addCriterion("pm_sal is null");
            return (Criteria) this;
        }

        public Criteria andPmSalIsNotNull() {
            addCriterion("pm_sal is not null");
            return (Criteria) this;
        }

        public Criteria andPmSalEqualTo(BigDecimal value) {
            addCriterion("pm_sal =", value, "pmSal");
            return (Criteria) this;
        }

        public Criteria andPmSalNotEqualTo(BigDecimal value) {
            addCriterion("pm_sal <>", value, "pmSal");
            return (Criteria) this;
        }

        public Criteria andPmSalGreaterThan(BigDecimal value) {
            addCriterion("pm_sal >", value, "pmSal");
            return (Criteria) this;
        }

        public Criteria andPmSalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pm_sal >=", value, "pmSal");
            return (Criteria) this;
        }

        public Criteria andPmSalLessThan(BigDecimal value) {
            addCriterion("pm_sal <", value, "pmSal");
            return (Criteria) this;
        }

        public Criteria andPmSalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pm_sal <=", value, "pmSal");
            return (Criteria) this;
        }

        public Criteria andPmSalIn(List<BigDecimal> values) {
            addCriterion("pm_sal in", values, "pmSal");
            return (Criteria) this;
        }

        public Criteria andPmSalNotIn(List<BigDecimal> values) {
            addCriterion("pm_sal not in", values, "pmSal");
            return (Criteria) this;
        }

        public Criteria andPmSalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pm_sal between", value1, value2, "pmSal");
            return (Criteria) this;
        }

        public Criteria andPmSalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pm_sal not between", value1, value2, "pmSal");
            return (Criteria) this;
        }

        public Criteria andPmAddressIsNull() {
            addCriterion("pm_address is null");
            return (Criteria) this;
        }

        public Criteria andPmAddressIsNotNull() {
            addCriterion("pm_address is not null");
            return (Criteria) this;
        }

        public Criteria andPmAddressEqualTo(String value) {
            addCriterion("pm_address =", value, "pmAddress");
            return (Criteria) this;
        }

        public Criteria andPmAddressNotEqualTo(String value) {
            addCriterion("pm_address <>", value, "pmAddress");
            return (Criteria) this;
        }

        public Criteria andPmAddressGreaterThan(String value) {
            addCriterion("pm_address >", value, "pmAddress");
            return (Criteria) this;
        }

        public Criteria andPmAddressGreaterThanOrEqualTo(String value) {
            addCriterion("pm_address >=", value, "pmAddress");
            return (Criteria) this;
        }

        public Criteria andPmAddressLessThan(String value) {
            addCriterion("pm_address <", value, "pmAddress");
            return (Criteria) this;
        }

        public Criteria andPmAddressLessThanOrEqualTo(String value) {
            addCriterion("pm_address <=", value, "pmAddress");
            return (Criteria) this;
        }

        public Criteria andPmAddressLike(String value) {
            addCriterion("pm_address like", value, "pmAddress");
            return (Criteria) this;
        }

        public Criteria andPmAddressNotLike(String value) {
            addCriterion("pm_address not like", value, "pmAddress");
            return (Criteria) this;
        }

        public Criteria andPmAddressIn(List<String> values) {
            addCriterion("pm_address in", values, "pmAddress");
            return (Criteria) this;
        }

        public Criteria andPmAddressNotIn(List<String> values) {
            addCriterion("pm_address not in", values, "pmAddress");
            return (Criteria) this;
        }

        public Criteria andPmAddressBetween(String value1, String value2) {
            addCriterion("pm_address between", value1, value2, "pmAddress");
            return (Criteria) this;
        }

        public Criteria andPmAddressNotBetween(String value1, String value2) {
            addCriterion("pm_address not between", value1, value2, "pmAddress");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNull() {
            addCriterion("company is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("company is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEqualTo(Integer value) {
            addCriterion("company =", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotEqualTo(Integer value) {
            addCriterion("company <>", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThan(Integer value) {
            addCriterion("company >", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(Integer value) {
            addCriterion("company >=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThan(Integer value) {
            addCriterion("company <", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThanOrEqualTo(Integer value) {
            addCriterion("company <=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyIn(List<Integer> values) {
            addCriterion("company in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotIn(List<Integer> values) {
            addCriterion("company not in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyBetween(Integer value1, Integer value2) {
            addCriterion("company between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotBetween(Integer value1, Integer value2) {
            addCriterion("company not between", value1, value2, "company");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table projectman
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 19:23:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table projectman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}