package com.woniuxy.entity;

public class Security {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security.pl_sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer plSid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security.pl_sname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String plSname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security.pl_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String plStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security.pl_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String plRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security.pl_sid
     *
     * @return the value of security.pl_sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getPlSid() {
        return plSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security.pl_sid
     *
     * @param plSid the value for security.pl_sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setPlSid(Integer plSid) {
        this.plSid = plSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security.project_id
     *
     * @return the value of security.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security.project_id
     *
     * @param projectId the value for security.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security.pl_sname
     *
     * @return the value of security.pl_sname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getPlSname() {
        return plSname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security.pl_sname
     *
     * @param plSname the value for security.pl_sname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setPlSname(String plSname) {
        this.plSname = plSname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security.pl_status
     *
     * @return the value of security.pl_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getPlStatus() {
        return plStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security.pl_status
     *
     * @param plStatus the value for security.pl_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setPlStatus(String plStatus) {
        this.plStatus = plStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security.company
     *
     * @return the value of security.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security.company
     *
     * @param company the value for security.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security.pl_remarks
     *
     * @return the value of security.pl_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getPlRemarks() {
        return plRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security.pl_remarks
     *
     * @param plRemarks the value for security.pl_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setPlRemarks(String plRemarks) {
        this.plRemarks = plRemarks;
    }
}