package com.woniuxy.entity;

import java.util.ArrayList;
import java.util.List;

public class SecurityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public SecurityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPlSidIsNull() {
            addCriterion("pl_sid is null");
            return (Criteria) this;
        }

        public Criteria andPlSidIsNotNull() {
            addCriterion("pl_sid is not null");
            return (Criteria) this;
        }

        public Criteria andPlSidEqualTo(Integer value) {
            addCriterion("pl_sid =", value, "plSid");
            return (Criteria) this;
        }

        public Criteria andPlSidNotEqualTo(Integer value) {
            addCriterion("pl_sid <>", value, "plSid");
            return (Criteria) this;
        }

        public Criteria andPlSidGreaterThan(Integer value) {
            addCriterion("pl_sid >", value, "plSid");
            return (Criteria) this;
        }

        public Criteria andPlSidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pl_sid >=", value, "plSid");
            return (Criteria) this;
        }

        public Criteria andPlSidLessThan(Integer value) {
            addCriterion("pl_sid <", value, "plSid");
            return (Criteria) this;
        }

        public Criteria andPlSidLessThanOrEqualTo(Integer value) {
            addCriterion("pl_sid <=", value, "plSid");
            return (Criteria) this;
        }

        public Criteria andPlSidIn(List<Integer> values) {
            addCriterion("pl_sid in", values, "plSid");
            return (Criteria) this;
        }

        public Criteria andPlSidNotIn(List<Integer> values) {
            addCriterion("pl_sid not in", values, "plSid");
            return (Criteria) this;
        }

        public Criteria andPlSidBetween(Integer value1, Integer value2) {
            addCriterion("pl_sid between", value1, value2, "plSid");
            return (Criteria) this;
        }

        public Criteria andPlSidNotBetween(Integer value1, Integer value2) {
            addCriterion("pl_sid not between", value1, value2, "plSid");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andPlSnameIsNull() {
            addCriterion("pl_sname is null");
            return (Criteria) this;
        }

        public Criteria andPlSnameIsNotNull() {
            addCriterion("pl_sname is not null");
            return (Criteria) this;
        }

        public Criteria andPlSnameEqualTo(String value) {
            addCriterion("pl_sname =", value, "plSname");
            return (Criteria) this;
        }

        public Criteria andPlSnameNotEqualTo(String value) {
            addCriterion("pl_sname <>", value, "plSname");
            return (Criteria) this;
        }

        public Criteria andPlSnameGreaterThan(String value) {
            addCriterion("pl_sname >", value, "plSname");
            return (Criteria) this;
        }

        public Criteria andPlSnameGreaterThanOrEqualTo(String value) {
            addCriterion("pl_sname >=", value, "plSname");
            return (Criteria) this;
        }

        public Criteria andPlSnameLessThan(String value) {
            addCriterion("pl_sname <", value, "plSname");
            return (Criteria) this;
        }

        public Criteria andPlSnameLessThanOrEqualTo(String value) {
            addCriterion("pl_sname <=", value, "plSname");
            return (Criteria) this;
        }

        public Criteria andPlSnameLike(String value) {
            addCriterion("pl_sname like", value, "plSname");
            return (Criteria) this;
        }

        public Criteria andPlSnameNotLike(String value) {
            addCriterion("pl_sname not like", value, "plSname");
            return (Criteria) this;
        }

        public Criteria andPlSnameIn(List<String> values) {
            addCriterion("pl_sname in", values, "plSname");
            return (Criteria) this;
        }

        public Criteria andPlSnameNotIn(List<String> values) {
            addCriterion("pl_sname not in", values, "plSname");
            return (Criteria) this;
        }

        public Criteria andPlSnameBetween(String value1, String value2) {
            addCriterion("pl_sname between", value1, value2, "plSname");
            return (Criteria) this;
        }

        public Criteria andPlSnameNotBetween(String value1, String value2) {
            addCriterion("pl_sname not between", value1, value2, "plSname");
            return (Criteria) this;
        }

        public Criteria andPlStatusIsNull() {
            addCriterion("pl_status is null");
            return (Criteria) this;
        }

        public Criteria andPlStatusIsNotNull() {
            addCriterion("pl_status is not null");
            return (Criteria) this;
        }

        public Criteria andPlStatusEqualTo(String value) {
            addCriterion("pl_status =", value, "plStatus");
            return (Criteria) this;
        }

        public Criteria andPlStatusNotEqualTo(String value) {
            addCriterion("pl_status <>", value, "plStatus");
            return (Criteria) this;
        }

        public Criteria andPlStatusGreaterThan(String value) {
            addCriterion("pl_status >", value, "plStatus");
            return (Criteria) this;
        }

        public Criteria andPlStatusGreaterThanOrEqualTo(String value) {
            addCriterion("pl_status >=", value, "plStatus");
            return (Criteria) this;
        }

        public Criteria andPlStatusLessThan(String value) {
            addCriterion("pl_status <", value, "plStatus");
            return (Criteria) this;
        }

        public Criteria andPlStatusLessThanOrEqualTo(String value) {
            addCriterion("pl_status <=", value, "plStatus");
            return (Criteria) this;
        }

        public Criteria andPlStatusLike(String value) {
            addCriterion("pl_status like", value, "plStatus");
            return (Criteria) this;
        }

        public Criteria andPlStatusNotLike(String value) {
            addCriterion("pl_status not like", value, "plStatus");
            return (Criteria) this;
        }

        public Criteria andPlStatusIn(List<String> values) {
            addCriterion("pl_status in", values, "plStatus");
            return (Criteria) this;
        }

        public Criteria andPlStatusNotIn(List<String> values) {
            addCriterion("pl_status not in", values, "plStatus");
            return (Criteria) this;
        }

        public Criteria andPlStatusBetween(String value1, String value2) {
            addCriterion("pl_status between", value1, value2, "plStatus");
            return (Criteria) this;
        }

        public Criteria andPlStatusNotBetween(String value1, String value2) {
            addCriterion("pl_status not between", value1, value2, "plStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNull() {
            addCriterion("company is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("company is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEqualTo(Integer value) {
            addCriterion("company =", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotEqualTo(Integer value) {
            addCriterion("company <>", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThan(Integer value) {
            addCriterion("company >", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(Integer value) {
            addCriterion("company >=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThan(Integer value) {
            addCriterion("company <", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThanOrEqualTo(Integer value) {
            addCriterion("company <=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyIn(List<Integer> values) {
            addCriterion("company in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotIn(List<Integer> values) {
            addCriterion("company not in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyBetween(Integer value1, Integer value2) {
            addCriterion("company between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotBetween(Integer value1, Integer value2) {
            addCriterion("company not between", value1, value2, "company");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table security
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 19:23:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table security
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}