package com.woniuxy.entity;

public class SecurityStockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_stock.pl_sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer plSid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_stock.pl_sid
     *
     * @return the value of security_stock.pl_sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getPlSid() {
        return plSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_stock.pl_sid
     *
     * @param plSid the value for security_stock.pl_sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setPlSid(Integer plSid) {
        this.plSid = plSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_stock.sid
     *
     * @return the value of security_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_stock.sid
     *
     * @param sid the value for security_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }
}