package com.woniuxy.entity;

public class Splicing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column splicing.p4_spid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer p4Spid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column splicing.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column splicing.p4_spname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p4Spname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column splicing.p4_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p4Status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column splicing.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column splicing.p4_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p4Remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column splicing.p4_spid
     *
     * @return the value of splicing.p4_spid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getP4Spid() {
        return p4Spid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column splicing.p4_spid
     *
     * @param p4Spid the value for splicing.p4_spid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP4Spid(Integer p4Spid) {
        this.p4Spid = p4Spid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column splicing.project_id
     *
     * @return the value of splicing.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column splicing.project_id
     *
     * @param projectId the value for splicing.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column splicing.p4_spname
     *
     * @return the value of splicing.p4_spname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP4Spname() {
        return p4Spname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column splicing.p4_spname
     *
     * @param p4Spname the value for splicing.p4_spname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP4Spname(String p4Spname) {
        this.p4Spname = p4Spname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column splicing.p4_status
     *
     * @return the value of splicing.p4_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP4Status() {
        return p4Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column splicing.p4_status
     *
     * @param p4Status the value for splicing.p4_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP4Status(String p4Status) {
        this.p4Status = p4Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column splicing.company
     *
     * @return the value of splicing.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column splicing.company
     *
     * @param company the value for splicing.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column splicing.p4_remarks
     *
     * @return the value of splicing.p4_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP4Remarks() {
        return p4Remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column splicing.p4_remarks
     *
     * @param p4Remarks the value for splicing.p4_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP4Remarks(String p4Remarks) {
        this.p4Remarks = p4Remarks;
    }
}