package com.woniuxy.entity;

public class SplicingStockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column splicing_stock.p4_spid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer p4Spid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column splicing_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column splicing_stock.p4_spid
     *
     * @return the value of splicing_stock.p4_spid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getP4Spid() {
        return p4Spid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column splicing_stock.p4_spid
     *
     * @param p4Spid the value for splicing_stock.p4_spid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP4Spid(Integer p4Spid) {
        this.p4Spid = p4Spid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column splicing_stock.sid
     *
     * @return the value of splicing_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column splicing_stock.sid
     *
     * @param sid the value for splicing_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }
}