package com.woniuxy.entity;

public class Stock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.sname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.snum
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer snum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.sid
     *
     * @return the value of stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.sid
     *
     * @param sid the value for stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.sname
     *
     * @return the value of stock.sname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.sname
     *
     * @param sname the value for stock.sname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.snum
     *
     * @return the value of stock.snum
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getSnum() {
        return snum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.snum
     *
     * @param snum the value for stock.snum
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setSnum(Integer snum) {
        this.snum = snum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.company
     *
     * @return the value of stock.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.company
     *
     * @param company the value for stock.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }
}