package com.woniuxy.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TrailermanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public TrailermanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTmIdIsNull() {
            addCriterion("tm_id is null");
            return (Criteria) this;
        }

        public Criteria andTmIdIsNotNull() {
            addCriterion("tm_id is not null");
            return (Criteria) this;
        }

        public Criteria andTmIdEqualTo(Integer value) {
            addCriterion("tm_id =", value, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdNotEqualTo(Integer value) {
            addCriterion("tm_id <>", value, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdGreaterThan(Integer value) {
            addCriterion("tm_id >", value, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tm_id >=", value, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdLessThan(Integer value) {
            addCriterion("tm_id <", value, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdLessThanOrEqualTo(Integer value) {
            addCriterion("tm_id <=", value, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdIn(List<Integer> values) {
            addCriterion("tm_id in", values, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdNotIn(List<Integer> values) {
            addCriterion("tm_id not in", values, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdBetween(Integer value1, Integer value2) {
            addCriterion("tm_id between", value1, value2, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tm_id not between", value1, value2, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmNameIsNull() {
            addCriterion("tm_name is null");
            return (Criteria) this;
        }

        public Criteria andTmNameIsNotNull() {
            addCriterion("tm_name is not null");
            return (Criteria) this;
        }

        public Criteria andTmNameEqualTo(String value) {
            addCriterion("tm_name =", value, "tmName");
            return (Criteria) this;
        }

        public Criteria andTmNameNotEqualTo(String value) {
            addCriterion("tm_name <>", value, "tmName");
            return (Criteria) this;
        }

        public Criteria andTmNameGreaterThan(String value) {
            addCriterion("tm_name >", value, "tmName");
            return (Criteria) this;
        }

        public Criteria andTmNameGreaterThanOrEqualTo(String value) {
            addCriterion("tm_name >=", value, "tmName");
            return (Criteria) this;
        }

        public Criteria andTmNameLessThan(String value) {
            addCriterion("tm_name <", value, "tmName");
            return (Criteria) this;
        }

        public Criteria andTmNameLessThanOrEqualTo(String value) {
            addCriterion("tm_name <=", value, "tmName");
            return (Criteria) this;
        }

        public Criteria andTmNameLike(String value) {
            addCriterion("tm_name like", value, "tmName");
            return (Criteria) this;
        }

        public Criteria andTmNameNotLike(String value) {
            addCriterion("tm_name not like", value, "tmName");
            return (Criteria) this;
        }

        public Criteria andTmNameIn(List<String> values) {
            addCriterion("tm_name in", values, "tmName");
            return (Criteria) this;
        }

        public Criteria andTmNameNotIn(List<String> values) {
            addCriterion("tm_name not in", values, "tmName");
            return (Criteria) this;
        }

        public Criteria andTmNameBetween(String value1, String value2) {
            addCriterion("tm_name between", value1, value2, "tmName");
            return (Criteria) this;
        }

        public Criteria andTmNameNotBetween(String value1, String value2) {
            addCriterion("tm_name not between", value1, value2, "tmName");
            return (Criteria) this;
        }

        public Criteria andTmSexIsNull() {
            addCriterion("tm_sex is null");
            return (Criteria) this;
        }

        public Criteria andTmSexIsNotNull() {
            addCriterion("tm_sex is not null");
            return (Criteria) this;
        }

        public Criteria andTmSexEqualTo(String value) {
            addCriterion("tm_sex =", value, "tmSex");
            return (Criteria) this;
        }

        public Criteria andTmSexNotEqualTo(String value) {
            addCriterion("tm_sex <>", value, "tmSex");
            return (Criteria) this;
        }

        public Criteria andTmSexGreaterThan(String value) {
            addCriterion("tm_sex >", value, "tmSex");
            return (Criteria) this;
        }

        public Criteria andTmSexGreaterThanOrEqualTo(String value) {
            addCriterion("tm_sex >=", value, "tmSex");
            return (Criteria) this;
        }

        public Criteria andTmSexLessThan(String value) {
            addCriterion("tm_sex <", value, "tmSex");
            return (Criteria) this;
        }

        public Criteria andTmSexLessThanOrEqualTo(String value) {
            addCriterion("tm_sex <=", value, "tmSex");
            return (Criteria) this;
        }

        public Criteria andTmSexLike(String value) {
            addCriterion("tm_sex like", value, "tmSex");
            return (Criteria) this;
        }

        public Criteria andTmSexNotLike(String value) {
            addCriterion("tm_sex not like", value, "tmSex");
            return (Criteria) this;
        }

        public Criteria andTmSexIn(List<String> values) {
            addCriterion("tm_sex in", values, "tmSex");
            return (Criteria) this;
        }

        public Criteria andTmSexNotIn(List<String> values) {
            addCriterion("tm_sex not in", values, "tmSex");
            return (Criteria) this;
        }

        public Criteria andTmSexBetween(String value1, String value2) {
            addCriterion("tm_sex between", value1, value2, "tmSex");
            return (Criteria) this;
        }

        public Criteria andTmSexNotBetween(String value1, String value2) {
            addCriterion("tm_sex not between", value1, value2, "tmSex");
            return (Criteria) this;
        }

        public Criteria andTmAgeIsNull() {
            addCriterion("tm_age is null");
            return (Criteria) this;
        }

        public Criteria andTmAgeIsNotNull() {
            addCriterion("tm_age is not null");
            return (Criteria) this;
        }

        public Criteria andTmAgeEqualTo(Integer value) {
            addCriterion("tm_age =", value, "tmAge");
            return (Criteria) this;
        }

        public Criteria andTmAgeNotEqualTo(Integer value) {
            addCriterion("tm_age <>", value, "tmAge");
            return (Criteria) this;
        }

        public Criteria andTmAgeGreaterThan(Integer value) {
            addCriterion("tm_age >", value, "tmAge");
            return (Criteria) this;
        }

        public Criteria andTmAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("tm_age >=", value, "tmAge");
            return (Criteria) this;
        }

        public Criteria andTmAgeLessThan(Integer value) {
            addCriterion("tm_age <", value, "tmAge");
            return (Criteria) this;
        }

        public Criteria andTmAgeLessThanOrEqualTo(Integer value) {
            addCriterion("tm_age <=", value, "tmAge");
            return (Criteria) this;
        }

        public Criteria andTmAgeIn(List<Integer> values) {
            addCriterion("tm_age in", values, "tmAge");
            return (Criteria) this;
        }

        public Criteria andTmAgeNotIn(List<Integer> values) {
            addCriterion("tm_age not in", values, "tmAge");
            return (Criteria) this;
        }

        public Criteria andTmAgeBetween(Integer value1, Integer value2) {
            addCriterion("tm_age between", value1, value2, "tmAge");
            return (Criteria) this;
        }

        public Criteria andTmAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("tm_age not between", value1, value2, "tmAge");
            return (Criteria) this;
        }

        public Criteria andTmPhoneIsNull() {
            addCriterion("tm_phone is null");
            return (Criteria) this;
        }

        public Criteria andTmPhoneIsNotNull() {
            addCriterion("tm_phone is not null");
            return (Criteria) this;
        }

        public Criteria andTmPhoneEqualTo(Integer value) {
            addCriterion("tm_phone =", value, "tmPhone");
            return (Criteria) this;
        }

        public Criteria andTmPhoneNotEqualTo(Integer value) {
            addCriterion("tm_phone <>", value, "tmPhone");
            return (Criteria) this;
        }

        public Criteria andTmPhoneGreaterThan(Integer value) {
            addCriterion("tm_phone >", value, "tmPhone");
            return (Criteria) this;
        }

        public Criteria andTmPhoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("tm_phone >=", value, "tmPhone");
            return (Criteria) this;
        }

        public Criteria andTmPhoneLessThan(Integer value) {
            addCriterion("tm_phone <", value, "tmPhone");
            return (Criteria) this;
        }

        public Criteria andTmPhoneLessThanOrEqualTo(Integer value) {
            addCriterion("tm_phone <=", value, "tmPhone");
            return (Criteria) this;
        }

        public Criteria andTmPhoneIn(List<Integer> values) {
            addCriterion("tm_phone in", values, "tmPhone");
            return (Criteria) this;
        }

        public Criteria andTmPhoneNotIn(List<Integer> values) {
            addCriterion("tm_phone not in", values, "tmPhone");
            return (Criteria) this;
        }

        public Criteria andTmPhoneBetween(Integer value1, Integer value2) {
            addCriterion("tm_phone between", value1, value2, "tmPhone");
            return (Criteria) this;
        }

        public Criteria andTmPhoneNotBetween(Integer value1, Integer value2) {
            addCriterion("tm_phone not between", value1, value2, "tmPhone");
            return (Criteria) this;
        }

        public Criteria andTmSalIsNull() {
            addCriterion("tm_sal is null");
            return (Criteria) this;
        }

        public Criteria andTmSalIsNotNull() {
            addCriterion("tm_sal is not null");
            return (Criteria) this;
        }

        public Criteria andTmSalEqualTo(BigDecimal value) {
            addCriterion("tm_sal =", value, "tmSal");
            return (Criteria) this;
        }

        public Criteria andTmSalNotEqualTo(BigDecimal value) {
            addCriterion("tm_sal <>", value, "tmSal");
            return (Criteria) this;
        }

        public Criteria andTmSalGreaterThan(BigDecimal value) {
            addCriterion("tm_sal >", value, "tmSal");
            return (Criteria) this;
        }

        public Criteria andTmSalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("tm_sal >=", value, "tmSal");
            return (Criteria) this;
        }

        public Criteria andTmSalLessThan(BigDecimal value) {
            addCriterion("tm_sal <", value, "tmSal");
            return (Criteria) this;
        }

        public Criteria andTmSalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("tm_sal <=", value, "tmSal");
            return (Criteria) this;
        }

        public Criteria andTmSalIn(List<BigDecimal> values) {
            addCriterion("tm_sal in", values, "tmSal");
            return (Criteria) this;
        }

        public Criteria andTmSalNotIn(List<BigDecimal> values) {
            addCriterion("tm_sal not in", values, "tmSal");
            return (Criteria) this;
        }

        public Criteria andTmSalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tm_sal between", value1, value2, "tmSal");
            return (Criteria) this;
        }

        public Criteria andTmSalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tm_sal not between", value1, value2, "tmSal");
            return (Criteria) this;
        }

        public Criteria andTmAddressIsNull() {
            addCriterion("tm_address is null");
            return (Criteria) this;
        }

        public Criteria andTmAddressIsNotNull() {
            addCriterion("tm_address is not null");
            return (Criteria) this;
        }

        public Criteria andTmAddressEqualTo(String value) {
            addCriterion("tm_address =", value, "tmAddress");
            return (Criteria) this;
        }

        public Criteria andTmAddressNotEqualTo(String value) {
            addCriterion("tm_address <>", value, "tmAddress");
            return (Criteria) this;
        }

        public Criteria andTmAddressGreaterThan(String value) {
            addCriterion("tm_address >", value, "tmAddress");
            return (Criteria) this;
        }

        public Criteria andTmAddressGreaterThanOrEqualTo(String value) {
            addCriterion("tm_address >=", value, "tmAddress");
            return (Criteria) this;
        }

        public Criteria andTmAddressLessThan(String value) {
            addCriterion("tm_address <", value, "tmAddress");
            return (Criteria) this;
        }

        public Criteria andTmAddressLessThanOrEqualTo(String value) {
            addCriterion("tm_address <=", value, "tmAddress");
            return (Criteria) this;
        }

        public Criteria andTmAddressLike(String value) {
            addCriterion("tm_address like", value, "tmAddress");
            return (Criteria) this;
        }

        public Criteria andTmAddressNotLike(String value) {
            addCriterion("tm_address not like", value, "tmAddress");
            return (Criteria) this;
        }

        public Criteria andTmAddressIn(List<String> values) {
            addCriterion("tm_address in", values, "tmAddress");
            return (Criteria) this;
        }

        public Criteria andTmAddressNotIn(List<String> values) {
            addCriterion("tm_address not in", values, "tmAddress");
            return (Criteria) this;
        }

        public Criteria andTmAddressBetween(String value1, String value2) {
            addCriterion("tm_address between", value1, value2, "tmAddress");
            return (Criteria) this;
        }

        public Criteria andTmAddressNotBetween(String value1, String value2) {
            addCriterion("tm_address not between", value1, value2, "tmAddress");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNull() {
            addCriterion("company is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("company is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEqualTo(Integer value) {
            addCriterion("company =", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotEqualTo(Integer value) {
            addCriterion("company <>", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThan(Integer value) {
            addCriterion("company >", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(Integer value) {
            addCriterion("company >=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThan(Integer value) {
            addCriterion("company <", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThanOrEqualTo(Integer value) {
            addCriterion("company <=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyIn(List<Integer> values) {
            addCriterion("company in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotIn(List<Integer> values) {
            addCriterion("company not in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyBetween(Integer value1, Integer value2) {
            addCriterion("company between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotBetween(Integer value1, Integer value2) {
            addCriterion("company not between", value1, value2, "company");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trailerman
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 19:23:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trailerman
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}