package com.woniuxy.entity;

import java.math.BigDecimal;

public class Trailerman {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailerman.tm_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer tmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailerman.tm_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String tmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailerman.tm_sex
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String tmSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailerman.tm_age
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer tmAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailerman.tm_phone
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer tmPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailerman.tm_sal
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private BigDecimal tmSal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailerman.tm_address
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String tmAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailerman.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailerman.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailerman.tm_id
     *
     * @return the value of trailerman.tm_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getTmId() {
        return tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailerman.tm_id
     *
     * @param tmId the value for trailerman.tm_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setTmId(Integer tmId) {
        this.tmId = tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailerman.tm_name
     *
     * @return the value of trailerman.tm_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getTmName() {
        return tmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailerman.tm_name
     *
     * @param tmName the value for trailerman.tm_name
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setTmName(String tmName) {
        this.tmName = tmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailerman.tm_sex
     *
     * @return the value of trailerman.tm_sex
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getTmSex() {
        return tmSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailerman.tm_sex
     *
     * @param tmSex the value for trailerman.tm_sex
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setTmSex(String tmSex) {
        this.tmSex = tmSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailerman.tm_age
     *
     * @return the value of trailerman.tm_age
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getTmAge() {
        return tmAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailerman.tm_age
     *
     * @param tmAge the value for trailerman.tm_age
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setTmAge(Integer tmAge) {
        this.tmAge = tmAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailerman.tm_phone
     *
     * @return the value of trailerman.tm_phone
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getTmPhone() {
        return tmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailerman.tm_phone
     *
     * @param tmPhone the value for trailerman.tm_phone
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setTmPhone(Integer tmPhone) {
        this.tmPhone = tmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailerman.tm_sal
     *
     * @return the value of trailerman.tm_sal
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public BigDecimal getTmSal() {
        return tmSal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailerman.tm_sal
     *
     * @param tmSal the value for trailerman.tm_sal
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setTmSal(BigDecimal tmSal) {
        this.tmSal = tmSal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailerman.tm_address
     *
     * @return the value of trailerman.tm_address
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getTmAddress() {
        return tmAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailerman.tm_address
     *
     * @param tmAddress the value for trailerman.tm_address
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setTmAddress(String tmAddress) {
        this.tmAddress = tmAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailerman.status
     *
     * @return the value of trailerman.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailerman.status
     *
     * @param status the value for trailerman.status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailerman.company
     *
     * @return the value of trailerman.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailerman.company
     *
     * @param company the value for trailerman.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }
}