package com.woniuxy.entity;

import java.util.Date;

public class Weather {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.date
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.weather
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String weather;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.date
     *
     * @return the value of weather.date
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.date
     *
     * @param date the value for weather.date
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.weather
     *
     * @return the value of weather.weather
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getWeather() {
        return weather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.weather
     *
     * @param weather the value for weather.weather
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setWeather(String weather) {
        this.weather = weather;
    }
}