package com.woniuxy.entity;

public class Welding {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column welding.p5_wid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer p5Wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column welding.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column welding.p5_wname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p5Wname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column welding.p5_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p5Status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column welding.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column welding.p5_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private String p5Remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welding.p5_wid
     *
     * @return the value of welding.p5_wid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getP5Wid() {
        return p5Wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welding.p5_wid
     *
     * @param p5Wid the value for welding.p5_wid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP5Wid(Integer p5Wid) {
        this.p5Wid = p5Wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welding.project_id
     *
     * @return the value of welding.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welding.project_id
     *
     * @param projectId the value for welding.project_id
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welding.p5_wname
     *
     * @return the value of welding.p5_wname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP5Wname() {
        return p5Wname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welding.p5_wname
     *
     * @param p5Wname the value for welding.p5_wname
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP5Wname(String p5Wname) {
        this.p5Wname = p5Wname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welding.p5_status
     *
     * @return the value of welding.p5_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP5Status() {
        return p5Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welding.p5_status
     *
     * @param p5Status the value for welding.p5_status
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP5Status(String p5Status) {
        this.p5Status = p5Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welding.company
     *
     * @return the value of welding.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welding.company
     *
     * @param company the value for welding.company
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setCompany(Integer company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welding.p5_remarks
     *
     * @return the value of welding.p5_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public String getP5Remarks() {
        return p5Remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welding.p5_remarks
     *
     * @param p5Remarks the value for welding.p5_remarks
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP5Remarks(String p5Remarks) {
        this.p5Remarks = p5Remarks;
    }
}