package com.woniuxy.entity;

public class WeldingStockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column welding_stock.p5_wid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer p5Wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column welding_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    private Integer sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welding_stock.p5_wid
     *
     * @return the value of welding_stock.p5_wid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getP5Wid() {
        return p5Wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welding_stock.p5_wid
     *
     * @param p5Wid the value for welding_stock.p5_wid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setP5Wid(Integer p5Wid) {
        this.p5Wid = p5Wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column welding_stock.sid
     *
     * @return the value of welding_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column welding_stock.sid
     *
     * @param sid the value for welding_stock.sid
     *
     * @mbggenerated Mon Aug 19 19:23:43 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }
}